Claude Query Language: CopyrightNode Class Reference
CopyrightNode Class Reference final
Public Member Functions
CopyrightNode (std::string license, std::string owner)
void accept (QueryVisitor &visitor) const override
const std::string & license () const
const std::string & owner () const
Public Member Functions inherited from QueryNode
virtual ~QueryNode ()=default
Private Attributes
std::string m_license
std::string m_owner
Detailed Description
Definition at line 158 of file cql.cpp.
Constructor & Destructor Documentation
CopyrightNode()
CopyrightNode::CopyrightNode (std::string license, std::string owner) inline explicit
Definition at line 160 of file cql.cpp.
        : m_license(std::move(license)), m_owner(std::move(owner)) {}
References license(), m_license, m_owner, and owner().
Member Function Documentation
accept()
void CopyrightNode::accept (QueryVisitor & visitor) const inline override virtual
Implements QueryNode.
Definition at line 163 of file cql.cpp.
{
        visitor.visit(*this);
    }
References QueryVisitor::visit().
license()
const std::string & CopyrightNode::license () const inline nodiscard
Definition at line 167 of file cql.cpp.
{ return m_license; }
References m_license.
Referenced by CopyrightNode(), and QueryCompiler::visit().
owner()
const std::string & CopyrightNode::owner () const inline nodiscard
Definition at line 168 of file cql.cpp.
{ return m_owner; }
References m_owner.
Referenced by CopyrightNode(), and QueryCompiler::visit().
Member Data Documentation
m_license
std::string CopyrightNode::m_license private
Definition at line 171 of file cql.cpp.
Referenced by CopyrightNode(), and license().
m_owner
std::string CopyrightNode::m_owner private
Definition at line 172 of file cql.cpp.
Referenced by CopyrightNode(), and owner().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/nodes.cpp