Claude Query Language: TestNode Class Reference
TestNode Class Reference final
Public Member Functions
TestNode (std::vector< std::string > test_cases)
void accept (QueryVisitor &visitor) const override
const std::vector< std::string > & test_cases () const
Public Member Functions inherited from QueryNode
virtual ~QueryNode ()=default
Private Attributes
std::vector< std::string > m_test_cases
Detailed Description
Definition at line 110 of file cql.cpp.
Constructor & Destructor Documentation
TestNode()
TestNode::TestNode (std::vector< std::string > test_cases) inline explicit
Definition at line 112 of file cql.cpp.
        : m_test_cases(std::move(test_cases)) {}
References m_test_cases, and test_cases().
Member Function Documentation
accept()
void TestNode::accept (QueryVisitor & visitor) const inline override virtual
Implements QueryNode.
Definition at line 115 of file cql.cpp.
{
        visitor.visit(*this);
    }
References QueryVisitor::visit().
test_cases()
const std::vector< std::string > & TestNode::test_cases () const inline nodiscard
Definition at line 119 of file cql.cpp.
{ return m_test_cases; }
References m_test_cases.
Referenced by TestNode(), and QueryCompiler::visit().
Member Data Documentation
m_test_cases
std::vector<std::string> TestNode::m_test_cases private
Definition at line 122 of file cql.cpp.
Referenced by test_cases(), and TestNode().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/nodes.cpp