Claude Query Language: CodeRequestNode Class Reference
CodeRequestNode Class Reference final
Public Member Functions
CodeRequestNode (std::string language, std::string description)
void accept (QueryVisitor &visitor) const override
const std::string & language () const
const std::string & description () const
Public Member Functions inherited from QueryNode
virtual ~QueryNode ()=default
Private Attributes
std::string m_language
std::string m_description
Detailed Description
Definition at line 76 of file cql.cpp.
Constructor & Destructor Documentation
CodeRequestNode()
CodeRequestNode::CodeRequestNode (std::string language, std::string description) inline explicit
Definition at line 78 of file cql.cpp.
        : m_language(std::move(language)), m_description(std::move(description)) {}
References description(), language(), m_description, and m_language.
Member Function Documentation
accept()
void CodeRequestNode::accept (QueryVisitor & visitor) const inline override virtual
Implements QueryNode.
Definition at line 81 of file cql.cpp.
{
        visitor.visit(*this);
    }
References QueryVisitor::visit().
description()
const std::string & CodeRequestNode::description () const inline nodiscard
Definition at line 86 of file cql.cpp.
{ return m_description; }
References m_description.
Referenced by CodeRequestNode(), and QueryCompiler::visit().
language()
const std::string & CodeRequestNode::language () const inline nodiscard
Definition at line 85 of file cql.cpp.
{ return m_language; }
References m_language.
Referenced by CodeRequestNode(), and QueryCompiler::visit().
Member Data Documentation
m_description
std::string CodeRequestNode::m_description private
Definition at line 90 of file cql.cpp.
Referenced by CodeRequestNode(), and description().
m_language
std::string CodeRequestNode::m_language private
Definition at line 89 of file cql.cpp.
Referenced by CodeRequestNode(), and language().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/nodes.cpp