Claude Query Language: Parser Class Reference
Parser Class Reference
Public Member Functions
Parser (const std::string_view input)
std::vector< std::unique_ptr< QueryNode > > parse ()
Private Member Functions
void advance ()
std::string parse_string ()
std::unique_ptr< QueryNode > parse_code_request ()
std::unique_ptr< QueryNode > parse_context ()
std::unique_ptr< QueryNode > parse_test ()
std::unique_ptr< QueryNode > parse_dependency ()
std::unique_ptr< QueryNode > parse_performance ()
std::unique_ptr< QueryNode > parse_copyright ()
Private Attributes
Lexer m_lexer
std::optional< Token > m_current_token
Detailed Description
Definition at line 469 of file cql.cpp.
Constructor & Destructor Documentation
Parser()
Parser::Parser (const std::string_view input) inline explicit
Definition at line 471 of file cql.cpp.
                                                : m_lexer(input) {
        advance();
    }
References advance(), and m_lexer.
Member Function Documentation
advance()
void Parser::advance () inline private
Definition at line 528 of file cql.cpp.
                   {
        m_current_token = m_lexer.next_token();
    }
References m_current_token, and m_lexer.
Referenced by parse(), parse_code_request(), parse_context(), parse_copyright(), parse_dependency(), parse_performance(), parse_string(), parse_test(), and Parser().
parse()
std::vector< std::unique_ptr< QueryNode > > Parser::parse () inline
Definition at line 475 of file cql.cpp.
{
        std::vector<std::unique_ptr<QueryNode>> nodes;
        while (m_current_token) {
            if (m_current_token->m_type == TokenType::NEWLINE) {
                advance();
                continue;
            }
            // validate the token is a keyword
            if (m_current_token->m_type != TokenType::LANGUAGE &&
                m_current_token->m_type != TokenType::DESCRIPTION &&
                m_current_token->m_type != TokenType::CONTEXT &&
                m_current_token->m_type != TokenType::TEST &&
                m_current_token->m_type != TokenType::DEPENDENCY &&
                m_current_token->m_type != TokenType::PERFORMANCE &&
                m_current_token->m_type != TokenType::COPYRIGHT) {
                throw std::runtime_error("Expected keyword at line " +
                    std::to_string(m_current_token->m_line));
            }
            // parse the appropriate node type
            switch (m_current_token->m_type) {
                case TokenType::LANGUAGE:
                    nodes.push_back(parse_code_request());
                    break;
                case TokenType::CONTEXT:
                    nodes.push_back(parse_context());
                    break;
                case TokenType::TEST:
                    nodes.push_back(parse_test());
                    break;
                case TokenType::DEPENDENCY:
                    nodes.push_back(parse_dependency());
                    break;
                case TokenType::PERFORMANCE:
                    nodes.push_back(parse_performance());
                    break;
                case TokenType::COPYRIGHT:
                    nodes.push_back(parse_copyright());
                    break;
                default:
                    throw std::runtime_error("Unexpected token type");
            }
        }
        return nodes;
    }
References advance(), CONTEXT, COPYRIGHT, DEPENDENCY, DESCRIPTION, LANGUAGE, m_current_token, NEWLINE, parse_code_request(), parse_context(), parse_copyright(), parse_dependency(), parse_performance(), parse_test(), PERFORMANCE, and TEST.
Referenced by query_examples(), cql::test::test_compiler(), test_compiler(), cql::test::test_parser(), and test_parser().
parse_code_request()
std::unique_ptr< QueryNode > Parser::parse_code_request () inline private
Definition at line 558 of file cql.cpp.
{
        advance(); // skip past @language token
        // get the language string
        std::string language = parse_string();
        // skip any newlines
        while (m_current_token && m_current_token->m_type == TokenType::NEWLINE) {
            advance();
        }
        // now expect @description
        if (!m_current_token || m_current_token->m_type != TokenType::DESCRIPTION) {
            throw std::runtime_error(
                "Expected @description after @language at line " +
                std::to_string(m_current_token ? m_current_token->m_line : 0) +
                (m_current_token ? " (got '" + m_current_token->m_value + "')" : "")
            );
        }
        advance(); // skip past @description token
        std::string description = parse_string();
        return std::make_unique<CodeRequestNode>(language, description);
    }
References advance(), DESCRIPTION, m_current_token, NEWLINE, and parse_string().
Referenced by parse().
parse_context()
std::unique_ptr< QueryNode > Parser::parse_context () inline private
Definition at line 585 of file cql.cpp.
{
        advance(); // skip @context
        std::string context = parse_string();
        return std::make_unique<ContextNode>(context);
    }
References advance(), and parse_string().
Referenced by parse().
parse_copyright()
std::unique_ptr< QueryNode > Parser::parse_copyright () inline private
Definition at line 621 of file cql.cpp.
{
        advance(); // skip @copyright
        std::string license = parse_string();
        std::string owner = parse_string();
        return std::make_unique<CopyrightNode>(license, owner);
    }
References advance(), and parse_string().
Referenced by parse().
parse_dependency()
std::unique_ptr< QueryNode > Parser::parse_dependency () inline private
Definition at line 603 of file cql.cpp.
{
        advance(); // skip @dependency
        std::vector<std::string> dependencies;
        // get the dependency
        dependencies.push_back(parse_string());
        return std::make_unique<DependencyNode>(std::move(dependencies));
    }
References advance(), and parse_string().
Referenced by parse().
parse_performance()
std::unique_ptr< QueryNode > Parser::parse_performance () inline private
Definition at line 614 of file cql.cpp.
{
        advance(); // skip @performance
        std::string requirement = parse_string();
        return std::make_unique<PerformanceNode>(requirement);
    }
References advance(), and parse_string().
Referenced by parse().
parse_string()
std::string Parser::parse_string () inline private
Definition at line 533 of file cql.cpp.
{
        // skip whitespace tokens
        while (m_current_token && m_current_token->m_type == TokenType::NEWLINE) {
            advance();
        }
        if (!m_current_token) {
            throw std::runtime_error("Unexpected end of input while expecting string");
        }
        if (m_current_token->m_type != TokenType::STRING) {
            throw std::runtime_error(
                "Expected string at line " + std::to_string(m_current_token->m_line) +
                ", column " + std::to_string(m_current_token->m_column) +
                " (got " + token_type_to_string(m_current_token->m_type) +
                " with value '" + m_current_token->m_value + "')"
            );
        }
        std::string value = m_current_token->m_value;
        advance(); // move to the next token
        return value;
    }
References advance(), m_current_token, NEWLINE, STRING, and token_type_to_string().
Referenced by parse_code_request(), parse_context(), parse_copyright(), parse_dependency(), parse_performance(), and parse_test().
parse_test()
std::unique_ptr< QueryNode > Parser::parse_test () inline private
Definition at line 592 of file cql.cpp.
{
        advance(); // skip @test
        std::vector<std::string> test_cases;
        // get the first test case
        test_cases.push_back(parse_string());
        return std::make_unique<TestNode>(std::move(test_cases));
    }
References advance(), and parse_string().
Referenced by parse().
Member Data Documentation
m_current_token
std::optional<Token> Parser::m_current_token private
Definition at line 526 of file cql.cpp.
Referenced by advance(), parse(), parse_code_request(), and parse_string().
m_lexer
Lexer Parser::m_lexer private
Definition at line 525 of file cql.cpp.
Referenced by advance(), and Parser().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/parser.cpp