Claude Query Language: Lexer Class Reference
Lexer Class Reference
Public Member Functions
Lexer (std::string_view input)
std::optional< Token > next_token ()
Private Member Functions
void advance ()
void skip_whitespace ()
std::optional< Token > lex_keyword ()
std::optional< Token > lex_string ()
std::optional< Token > lex_identifier ()
Private Attributes
std::string_view m_input
size_t m_current
size_t m_line
size_t m_column
Detailed Description
Definition at line 339 of file cql.cpp.
Constructor & Destructor Documentation
Lexer()
Lexer::Lexer (std::string_view input) inline explicit
Definition at line 341 of file cql.cpp.
        : m_input(input), m_current(0), m_line(1), m_column(1) {}
References m_column, m_current, m_input, and m_line.
Member Function Documentation
advance()
void Lexer::advance () inline private
Definition at line 377 of file cql.cpp.
                   {
        m_current++;
        m_column++;
    }
References m_column, and m_current.
Referenced by lex_identifier(), lex_keyword(), lex_string(), next_token(), and skip_whitespace().
lex_identifier()
std::optional< Token > Lexer::lex_identifier () inline private
Definition at line 453 of file cql.cpp.
{
        std::string value;
        const size_t start_column = m_column;
        while (m_current < m_input.length() &&
               !std::isspace(m_input[m_current]) &&
               m_input[m_current] != '@') {
            value += m_input[m_current];
            advance();
        }
        return Token(TokenType::IDENTIFIER, value, m_line, start_column);
    }
References advance(), IDENTIFIER, m_column, m_current, m_input, and m_line.
Referenced by next_token().
lex_keyword()
std::optional< Token > Lexer::lex_keyword () inline private
Definition at line 391 of file cql.cpp.
{
        advance(); // skip @
        std::string keyword;
        size_t start_column = m_column;
        while (m_current < m_input.length() && std::isalpha(m_input[m_current])) {
            keyword += m_input[m_current];
            advance();
        }
        TokenType type;
        if (keyword == "language") type = TokenType::LANGUAGE;
        else if (keyword == "description") type = TokenType::DESCRIPTION;
        else if (keyword == "context") type = TokenType::CONTEXT;
        else if (keyword == "test") type = TokenType::TEST;
        else if (keyword == "dependency") type = TokenType::DEPENDENCY;
        else if (keyword == "performance") type = TokenType::PERFORMANCE;
        else if (keyword == "copyright") type = TokenType::COPYRIGHT;
        else throw std::runtime_error("Unknown keyword: @" + keyword);
        return Token(type, keyword, m_line, start_column);
    }
References advance(), CONTEXT, COPYRIGHT, DEPENDENCY, DESCRIPTION, LANGUAGE, m_column, m_current, m_input, m_line, PERFORMANCE, and TEST.
Referenced by next_token().
lex_string()
std::optional< Token > Lexer::lex_string () inline private
Definition at line 415 of file cql.cpp.
{
        if (m_current >= m_input.length() || m_input[m_current] != '"') {
            throw std::runtime_error("Expected opening quote at line " +
                std::to_string(m_line) + ", column " + std::to_string(m_column));
        }
        advance(); // skip opening quote
        std::string value;
        const size_t start_column = m_column;
        while (m_current < m_input.length() && m_input[m_current] != '"') {
            if (m_input[m_current] == '\\') {
                advance();
                if (m_current >= m_input.length()) {
                    throw std::runtime_error("Unterminated string escape sequence");
                }
                switch (m_input[m_current]) {
                    case 'n': value += '\n'; break;
                    case 't': value += '\t'; break;
                    case '"': value += '"'; break;
                    case '\\': value += '\\'; break;
                    default: throw std::runtime_error("Invalid escape sequence");
                }
            } else {
                value += m_input[m_current];
            }
            advance();
        }
        if (m_current >= m_input.length()) {
            throw std::runtime_error("Unterminated string");
        }
        advance(); // skip closing quote
        return Token(TokenType::STRING, value, m_line, start_column);
    }
References advance(), m_column, m_current, m_input, m_line, and STRING.
Referenced by next_token().
next_token()
std::optional< Token > Lexer::next_token () inline
Definition at line 344 of file cql.cpp.
{
        skip_whitespace();
        if (m_current >= m_input.length()) {
            return std::nullopt;
        }
        if (m_input[m_current] == '@') {
            return lex_keyword();
        }
        if (m_input[m_current] == '"') {
            return lex_string();
        }
        if (m_input[m_current] == '\n') {
            auto token = Token(TokenType::NEWLINE, "\n", m_line, m_column);
            advance();
            m_line++;
            m_column = 1;
            return token;
        }
        return lex_identifier();
    }
References advance(), lex_identifier(), lex_keyword(), lex_string(), m_column, m_current, m_input, m_line, NEWLINE, and skip_whitespace().
Referenced by cql::test::test_lexer(), and test_lexer().
skip_whitespace()
void Lexer::skip_whitespace () inline private
Definition at line 383 of file cql.cpp.
{
        while (m_current < m_input.length() &&
               (std::isspace(m_input[m_current]) && m_input[m_current] != '\n')) {
            advance();
        }
    }
References advance(), m_current, and m_input.
Referenced by next_token().
Member Data Documentation
m_column
size_t Lexer::m_column private
Definition at line 374 of file cql.cpp.
Referenced by advance(), lex_identifier(), lex_keyword(), lex_string(), Lexer(), and next_token().
m_current
size_t Lexer::m_current private
Definition at line 372 of file cql.cpp.
Referenced by advance(), lex_identifier(), lex_keyword(), lex_string(), Lexer(), next_token(), and skip_whitespace().
m_input
std::string_view Lexer::m_input private
Definition at line 371 of file cql.cpp.
Referenced by lex_identifier(), lex_keyword(), lex_string(), Lexer(), next_token(), and skip_whitespace().
m_line
size_t Lexer::m_line private
Definition at line 373 of file cql.cpp.
Referenced by lex_identifier(), lex_keyword(), lex_string(), Lexer(), and next_token().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/lexer.cpp