Claude Query Language: PerformanceNode Class Reference
PerformanceNode Class Reference final
Public Member Functions
PerformanceNode (std::string requirement)
void accept (QueryVisitor &visitor) const override
const std::string & requirement () const
Public Member Functions inherited from QueryNode
virtual ~QueryNode ()=default
Private Attributes
std::string m_requirement
Detailed Description
Definition at line 142 of file cql.cpp.
Constructor & Destructor Documentation
PerformanceNode()
PerformanceNode::PerformanceNode (std::string requirement) inline explicit
Definition at line 144 of file cql.cpp.
        : m_requirement(std::move(requirement)) {}
References m_requirement, and requirement().
Member Function Documentation
accept()
void PerformanceNode::accept (QueryVisitor & visitor) const inline override virtual
Implements QueryNode.
Definition at line 147 of file cql.cpp.
{
        visitor.visit(*this);
    }
References QueryVisitor::visit().
requirement()
const std::string & PerformanceNode::requirement () const inline nodiscard
Definition at line 151 of file cql.cpp.
{ return m_requirement; }
References m_requirement.
Referenced by PerformanceNode(), and QueryCompiler::visit().
Member Data Documentation
m_requirement
std::string PerformanceNode::m_requirement private
Definition at line 154 of file cql.cpp.
Referenced by PerformanceNode(), and requirement().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/nodes.cpp