Claude Query Language: ContextNode Class Reference
ContextNode Class Reference final
Public Member Functions
ContextNode (std::string context)
void accept (QueryVisitor &visitor) const override
const std::string & context () const
Public Member Functions inherited from QueryNode
virtual ~QueryNode ()=default
Private Attributes
std::string m_context
Detailed Description
Definition at line 94 of file cql.cpp.
Constructor & Destructor Documentation
ContextNode()
ContextNode::ContextNode (std::string context) inline explicit
Definition at line 96 of file cql.cpp.
        : m_context(std::move(context)) {}
References context(), and m_context.
Member Function Documentation
accept()
void ContextNode::accept (QueryVisitor & visitor) const inline override virtual
Implements QueryNode.
Definition at line 99 of file cql.cpp.
{
        visitor.visit(*this);
    }
References QueryVisitor::visit().
context()
const std::string & ContextNode::context () const inline nodiscard
Definition at line 103 of file cql.cpp.
{ return m_context; }
References m_context.
Referenced by ContextNode(), and QueryCompiler::visit().
Member Data Documentation
m_context
std::string ContextNode::m_context private
Definition at line 106 of file cql.cpp.
Referenced by context(), and ContextNode().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/nodes.cpp