Claude Query Language: QueryCompiler Class Reference
QueryCompiler Class Reference final
Public Member Functions
void visit (const CodeRequestNode &node) override
void visit (const ContextNode &node) override
void visit (const TestNode &node) override
void visit (const DependencyNode &node) override
void visit (const PerformanceNode &node) override
void visit (const CopyrightNode &node) override
std::string get_compiled_query () const
void print_compiled_query (std::ostream &out=std::cout) const
Public Member Functions inherited from QueryVisitor
virtual ~QueryVisitor ()=default
Private Attributes
std::map< std::string, std::string > m_result_sections
std::vector< std::string > m_test_cases
Detailed Description
Definition at line 176 of file cql.cpp.
Member Function Documentation
get_compiled_query()
std::string QueryCompiler::get_compiled_query () const inline nodiscard
Definition at line 222 of file cql.cpp.
{
        std::string query_string;
        // add a copyright section if it exists
        auto copyright_it = m_result_sections.find("copyright");
        if (copyright_it != m_result_sections.end()) {
            query_string += copyright_it->second;
        }
        // add a code section if it exists
        auto code_it = m_result_sections.find("code");
        if (code_it != m_result_sections.end()) {
            query_string += code_it->second;
        }
        // add a context section if it exists
        auto context_it = m_result_sections.find("context");
        if (context_it != m_result_sections.end()) {
            query_string += context_it->second + "\n";
        }
        // add a dependencies section if it exists
        auto dependencies_it = m_result_sections.find("dependencies");
        if (dependencies_it != m_result_sections.end()) {
            query_string += dependencies_it->second + "\n";
        }
        // add a performance section if it exists
        auto performance_it = m_result_sections.find("performance");
        if (performance_it != m_result_sections.end()) {
            query_string += performance_it->second + "\n";
        }
        // add test cases if we have any
        if (!m_test_cases.empty()) {
            query_string += "Please include tests for the following cases:\n";
            for (const auto& test_case : m_test_cases) {
                query_string += "- " + test_case + "\n";
            }
            query_string += "\n";
        }
        // add a quality assurance section as a standard footer
        query_string += "Quality Assurance Requirements:\n";
        query_string += "- All code must be well-documented with comments\n";
        query_string += "- Follow modern C++ best practices\n";
        query_string += "- Ensure proper error handling\n";
        query_string += "- Optimize for readability and maintainability\n";
        return query_string;
    }
References m_result_sections, and m_test_cases.
Referenced by print_compiled_query(), query_examples(), cql::test::test_compiler(), and test_compiler().
print_compiled_query()
void QueryCompiler::print_compiled_query (std::ostream & out = std::cout) const inline
Definition at line 274 of file cql.cpp.
{
        out << "\n=== Compiled Query ===\n\n"
            << get_compiled_query()
            << "===================\n";
    }
References get_compiled_query().
visit() [1/6]
void QueryCompiler::visit (const CodeRequestNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 178 of file cql.cpp.
{
        m_result_sections["code"] = "Please generate " + node.language() + " code that:\n" +
                                 node.description() + "\n\n";
    }
References CodeRequestNode::description(), CodeRequestNode::language(), and m_result_sections.
visit() [2/6]
void QueryCompiler::visit (const ContextNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 183 of file cql.cpp.
{
        if (!m_result_sections.count("context")) {
            m_result_sections["context"] = "Context:\n";
        }
        m_result_sections["context"] += "- " + node.context() + "\n";
    }
References ContextNode::context(), and m_result_sections.
visit() [3/6]
void QueryCompiler::visit (const CopyrightNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 213 of file cql.cpp.
{
        std::string copyright_message = "Please include the following copyright header at the top of all generated files:\n";
        copyright_message += "```\n";
        copyright_message += "// " + node.license() + "\n";
        copyright_message += "// Copyright (c) " + node.owner() + "\n";
        copyright_message += "```\n\n";
        m_result_sections["copyright"] = copyright_message;
    }
References CopyrightNode::license(), m_result_sections, and CopyrightNode::owner().
visit() [4/6]
void QueryCompiler::visit (const DependencyNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 197 of file cql.cpp.
{
        if (!m_result_sections.count("dependencies")) {
            m_result_sections["dependencies"] = "Dependencies:\n";
        }
        for (const auto& dependency : node.dependencies()) {
            m_result_sections["dependencies"] += "- " + dependency + "\n";
        }
    }
References DependencyNode::dependencies(), and m_result_sections.
visit() [5/6]
void QueryCompiler::visit (const PerformanceNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 206 of file cql.cpp.
{
        if (!m_result_sections.count("performance")) {
            m_result_sections["performance"] = "Performance Requirements:\n";
        }
        m_result_sections["performance"] += "- " + node.requirement() + "\n";
    }
References m_result_sections, and PerformanceNode::requirement().
visit() [6/6]
void QueryCompiler::visit (const TestNode & node) inline override virtual
Implements QueryVisitor.
Definition at line 190 of file cql.cpp.
{
        // store the test cases, we'll format them when getting the final query
        m_test_cases.insert(m_test_cases.end(),
                          node.test_cases().begin(),
                          node.test_cases().end());
    }
References m_test_cases, and TestNode::test_cases().
Member Data Documentation
m_result_sections
std::map<std::string, std::string> QueryCompiler::m_result_sections private
Definition at line 281 of file cql.cpp.
Referenced by get_compiled_query(), visit(), visit(), visit(), visit(), and visit().
m_test_cases
std::vector<std::string> QueryCompiler::m_test_cases private
Definition at line 282 of file cql.cpp.
Referenced by get_compiled_query(), and visit().
The documentation for this class was generated from the following files:
src/cql.cpp
src/cql/compiler.cpp