Claude Query Language: src/cql.cpp File Reference
cql.cpp File Reference
#include <map>
#include <cassert>
#include "include/cql/cql.hpp"
Classes
class QueryVisitor
class QueryNode
class CodeRequestNode
class ContextNode
class TestNode
class DependencyNode
class PerformanceNode
class CopyrightNode
class QueryCompiler
struct Token
class Lexer
class Parser
Macros
#define CQL_HPP
Enumerations
enum class TokenType {
LANGUAGE , DESCRIPTION , CONTEXT , TEST ,
DEPENDENCY , PERFORMANCE , COPYRIGHT , IDENTIFIER ,
STRING , NEWLINE , END
}
Functions
std::string token_type_to_string (TokenType type)
bool contains (const std::string &str, const std::string &substr)
std::string read_file (const std::string &filepath)
void write_file (const std::string &filepath, const std::string &content)
void test_lexer ()
void test_parser ()
void test_compiler ()
void run_tests ()
void query_examples ()
Macro Definition Documentation
CQL_HPP
#define CQL_HPP
Definition at line 9 of file cql.cpp.
Enumeration Type Documentation
TokenType
enum class TokenType strong
Enumerator
LANGUAGE
DESCRIPTION
CONTEXT
TEST
DEPENDENCY
PERFORMANCE
COPYRIGHT
IDENTIFIER
STRING
NEWLINE
END
Definition at line 286 of file cql.cpp.
                     {
    LANGUAGE,       // @language
    DESCRIPTION,    // @description
    CONTEXT,        // @context
    TEST,           // @test
    DEPENDENCY,     // @dependency
    PERFORMANCE,    // @performance
    COPYRIGHT,      // @copyright
    IDENTIFIER,     // any text
    STRING,         // "quoted text"
    NEWLINE,        // \n
    END             // end of input
};
Function Documentation
contains()
bool contains (const std::string & str, const std::string & substr)
Definition at line 630 of file cql.cpp.
{
    return str.find(substr) != std::string::npos;
}
Referenced by test_compiler().
query_examples()
void query_examples ()
Definition at line 925 of file cql.cpp.
                      {
    Logger::getInstance().log(LogLevel::INFO, "\n=== Query Examples ===");
    // example 1: simple function query
    Logger::getInstance().log(LogLevel::INFO, "\nExample 1 - Simple Function:");
    std::string simple_query =
        "@language \"C++\"\n"
        "@description \"implement a string reverse function\"\n"
        "@context \"Using string_view for efficiency\"\n"
        "@test \"Empty string\"\n"
        "@test \"Single character\"\n"
        "@test \"Multiple characters\"\n";
    try {
        Parser parser1(simple_query);
        auto nodes = parser1.parse();
        QueryCompiler compiler1;
        for (const auto& node : nodes) {
            node->accept(compiler1);
        }
        Logger::getInstance().log(LogLevel::INFO, "Input DSL:\n", simple_query);
        std::string result = compiler1.get_compiled_query();
        Logger::getInstance().log(LogLevel::INFO, "\n=== Compiled Query ===\n\n", result, "\n===================");
    } catch (const std::exception& e) {
        Logger::getInstance().log(LogLevel::ERROR, "Error: ", e.what());
    }
    // example 2: class implementation query
    Logger::getInstance().log(LogLevel::INFO, "\nExample 2 - Class Implementation:");
    std::string class_query =
        "@language \"C++\"\n"
        "@description \"implement a thread-safe queue class with a maximum size\"\n"
        "@context \"Using C++20 features and RAII principles\"\n"
        "@context \"Must be exception-safe\"\n"
        "@dependency \"std::mutex, std::condition_variable\"\n"
        "@performance \"Support 100k operations per second\"\n"
        "@test \"Test concurrent push operations\"\n"
        "@test \"Test concurrent pop operations\"\n"
        "@test \"Test boundary conditions (empty/full)\"\n"
        "@test \"Test exception safety guarantees\"\n";
    try {
        Parser parser2(class_query);
        auto nodes = parser2.parse();
        QueryCompiler compiler2;
        for (const auto& node : nodes) {
            node->accept(compiler2);
        }
        Logger::getInstance().log(LogLevel::INFO, "Input DSL:\n", class_query);
        std::string result = compiler2.get_compiled_query();
        Logger::getInstance().log(LogLevel::INFO, "\n=== Compiled Query ===\n\n", result, "\n===================");
    } catch (const std::exception& e) {
        Logger::getInstance().log(LogLevel::ERROR, "Error: ", e.what());
    }
    // example 3: with copyright and license
    Logger::getInstance().log(LogLevel::INFO, "\nExample 3 - With Copyright and License:");
    std::string copyright_query =
        "@copyright \"MIT License\" \"2025 dbjwhs\"\n"
        "@language \"C++\"\n"
        "@description \"implement a binary search tree\"\n"
        "@context \"Modern C++ implementation\"\n"
        "@test \"Insert elements\"\n"
        "@test \"Delete elements\"\n"
        "@test \"Find elements\"\n";
    try {
        Parser parser3(copyright_query);
        auto nodes = parser3.parse();
        QueryCompiler compiler3;
        for (const auto& node : nodes) {
            node->accept(compiler3);
        }
        Logger::getInstance().log(LogLevel::INFO, "Input DSL:\n", copyright_query);
        std::string result = compiler3.get_compiled_query();
        Logger::getInstance().log(LogLevel::INFO, "\n=== Compiled Query ===\n\n", result, "\n===================");
    } catch (const std::exception& e) {
        Logger::getInstance().log(LogLevel::ERROR, "Error: ", e.what());
    }
}
References QueryCompiler::get_compiled_query(), and Parser::parse().
read_file()
std::string read_file (const std::string & filepath)
Definition at line 635 of file cql.cpp.
{
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open file: " + filepath);
    }
    return {std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()};
}
run_tests()
void run_tests ()
Definition at line 909 of file cql.cpp.
                 {
    Logger::getInstance().log(LogLevel::INFO, "Starting CQL test suite");
    try {
        test_lexer();
        test_parser();
        test_compiler();
        Logger::getInstance().log(LogLevel::INFO, "All tests passed!");
    } catch (const std::exception& e) {
        Logger::getInstance().log(LogLevel::ERROR, "Test failed: ", e.what());
        throw; // rethrow to signal test failure
    }
}
References test_compiler(), test_lexer(), and test_parser().
test_compiler()
void test_compiler ()
Definition at line 811 of file cql.cpp.
                     {
    Logger::getInstance().log(LogLevel::INFO, "Running compiler tests...");
    // test basic compilation
    {
        std::string input = R"(
            @language "C++"
            @description "implement a thread-safe queue"
            @context "Using Modern C++ features"
            @test "Test empty queue"
        )";
        Parser parser(input);
        auto nodes = parser.parse();
        QueryCompiler compiler;
        for (const auto& node : nodes) {
            node->accept(compiler);
        }
        std::string result = compiler.get_compiled_query();
        // verify the compiled query contains expected sections
        assert(contains(result, "Please generate C++ code that:"));
        assert(contains(result, "implement a thread-safe queue"));
        assert(contains(result, "Context:"));
        assert(contains(result, "Using Modern C++ features"));
        assert(contains(result, "Please include tests for the following cases:"));
        assert(contains(result, "Test empty queue"));
        Logger::getInstance().log(LogLevel::DEBUG, "Compiled query: ", result);
    }
    // test extended compilation with new node types
    {
        std::string input = R"(
            @language "C++"
            @description "implement a real-time data processor"
            @context "Embedded system environment"
            @dependency "boost::asio"
            @performance "Process 10k messages/second"
            @test "Test throughput under load"
        )";
        Parser parser(input);
        auto nodes = parser.parse();
        QueryCompiler compiler;
        for (const auto& node : nodes) {
            node->accept(compiler);
        }
        std::string result = compiler.get_compiled_query();
        // verify the compiled query contains expected sections
        assert(contains(result, "Please generate C++ code that:"));
        assert(contains(result, "implement a real-time data processor"));
        assert(contains(result, "Context:"));
        assert(contains(result, "Embedded system environment"));
        assert(contains(result, "Dependencies:"));
        assert(contains(result, "boost::asio"));
        assert(contains(result, "Performance Requirements:"));
        assert(contains(result, "Process 10k messages/second"));
        Logger::getInstance().log(LogLevel::DEBUG, "Compiled query: ", result);
    }
    // test compiler copyright
    {
        std::string input = R"(
            @copyright "MIT License" "2025 dbjwhs"
            @language "C++"
            @description "implement a thread-safe queue"
        )";
        Parser parser(input);
        auto nodes = parser.parse();
        QueryCompiler compiler;
        for (const auto& node : nodes) {
            node->accept(compiler);
        }
        std::string result = compiler.get_compiled_query();
        // verify the compiled query contains expected sections
        assert(contains(result, "Please include the following copyright header"));
        assert(contains(result, "MIT License"));
        assert(contains(result, "Copyright (c) 2025 dbjwhs"));
        assert(contains(result, "Please generate C++ code that:"));
        Logger::getInstance().log(LogLevel::DEBUG, "Compiled query with copyright: ", result);
    }
    Logger::getInstance().log(LogLevel::INFO, "Compiler tests passed!");
}
References contains(), QueryCompiler::get_compiled_query(), and Parser::parse().
Referenced by run_tests(), and cql::test::test_compiler_standalone().
test_lexer()
void test_lexer ()
Definition at line 653 of file cql.cpp.
                  {
    Logger::getInstance().log(LogLevel::INFO, "Running lexer tests...");
    // test basic tokenization
    {
        std::string input = "@language \"C++\"\n@description \"implement a stack\"";
        Lexer lexer(input);
        auto token1 = lexer.next_token();
        assert(token1 && token1->m_type == TokenType::LANGUAGE);
        Logger::getInstance().log(LogLevel::DEBUG, "Token 1: ", token1->to_string());
        auto token2 = lexer.next_token();
        assert(token2 && token2->m_type == TokenType::STRING && token2->m_value == "C++");
        Logger::getInstance().log(LogLevel::DEBUG, "Token 2: ", token2->to_string());
        auto token3 = lexer.next_token();
        assert(token3 && token3->m_type == TokenType::NEWLINE);
        Logger::getInstance().log(LogLevel::DEBUG, "Token 3: ", token3->to_string());
        auto token4 = lexer.next_token();
        assert(token4 && token4->m_type == TokenType::DESCRIPTION);
        auto token5 = lexer.next_token();
        assert(token5 && token5->m_type == TokenType::STRING && token5->m_value == "implement a stack");
        auto token6 = lexer.next_token();
        assert(!token6);
    }
    // test string escape sequences
    {
        std::string input = "@language \"C++\\n with newline\"";
        Lexer lexer(input);
        auto token1 = lexer.next_token();
        assert(token1 && token1->m_type == TokenType::LANGUAGE);
        auto token2 = lexer.next_token();
        assert(token2 && token2->m_type == TokenType::STRING);
        assert(token2->m_value == "C++\n with newline");
    }
    // test error handling - unterminated string
    try {
        std::string input = "@language \"unterminated string";
        Lexer lexer(input);
        lexer.next_token(); // @language
        lexer.next_token(); // should throw
        assert(false && "Expected exception for unterminated string");
    } catch (const std::runtime_error& e) {
        Logger::getInstance().log(LogLevel::DEBUG, "Expected exception: ", e.what());
    }
    // test new tokens
    {
        std::string input = "@dependency \"boost::asio\"\n@performance \"latency < 5ms\"";
        Lexer lexer(input);
        auto token1 = lexer.next_token();
        assert(token1 && token1->m_type == TokenType::DEPENDENCY);
        auto token2 = lexer.next_token();
        assert(token2 && token2->m_type == TokenType::STRING && token2->m_value == "boost::asio");
        auto token3 = lexer.next_token();
        assert(token3 && token3->m_type == TokenType::NEWLINE);
        auto token4 = lexer.next_token();
        assert(token4 && token4->m_type == TokenType::PERFORMANCE);
        auto token5 = lexer.next_token();
        assert(token5 && token5->m_type == TokenType::STRING && token5->m_value == "latency < 5ms");
    }
    // test copyright token
    {
        std::string input = "@copyright \"MIT License\" \"2025 dbjwhs\"";
        Lexer lexer(input);
        auto token1 = lexer.next_token();
        assert(token1 && token1->m_type == TokenType::COPYRIGHT);
        auto token2 = lexer.next_token();
        assert(token2 && token2->m_type == TokenType::STRING && token2->m_value == "MIT License");
        auto token3 = lexer.next_token();
        assert(token3 && token3->m_type == TokenType::STRING && token3->m_value == "2025 dbjwhs");
    }
    Logger::getInstance().log(LogLevel::INFO, "Lexer tests passed!");
}
References COPYRIGHT, DEPENDENCY, DESCRIPTION, LANGUAGE, NEWLINE, Lexer::next_token(), PERFORMANCE, and STRING.
Referenced by run_tests(), and cql::test::test_lexer_standalone().
test_parser()
void test_parser ()
Definition at line 747 of file cql.cpp.
                   {
    Logger::getInstance().log(LogLevel::INFO, "Running parser tests...");
    // test basic parsing
    {
        std::string input = R"(
            @language "C++"
            @description "implement a thread-safe queue"
            @context "Using Modern C++ features"
            @test "Test empty queue"
            @dependency "std::mutex"
            @performance "Handle 1M operations per second"
        )";
        Parser parser(input);
        auto nodes = parser.parse();
        assert(nodes.size() == 5);
        Logger::getInstance().log(LogLevel::DEBUG, "Parsed ", nodes.size(), " nodes");
        // verify node types
        auto* code_request = dynamic_cast<CodeRequestNode*>(nodes[0].get());
        assert(code_request && code_request->language() == "C++");
        assert(code_request->description() == "implement a thread-safe queue");
        auto* context = dynamic_cast<ContextNode*>(nodes[1].get());
        assert(context && context->context() == "Using Modern C++ features");
        auto* test = dynamic_cast<TestNode*>(nodes[2].get());
        assert(test && test->test_cases().size() == 1);
        assert(test->test_cases()[0] == "Test empty queue");
        auto* dependency = dynamic_cast<DependencyNode*>(nodes[3].get());
        assert(dependency && dependency->dependencies().size() == 1);
        assert(dependency->dependencies()[0] == "std::mutex");
        auto* performance = dynamic_cast<PerformanceNode*>(nodes[4].get());
        assert(performance && performance->requirement() == "Handle 1M operations per second");
    }
    // test error handling - missing description
    try {
        std::string input = "@language \"C++\"";
        Parser parser(input);
        parser.parse();
        assert(false && "Expected exception for missing description");
    } catch (const std::runtime_error& e) {
        Logger::getInstance().log(LogLevel::DEBUG, "Expected exception: ", e.what());
    }
    // test error handling - invalid token
    try {
        std::string input = "@invalid \"test\"";
        Parser parser(input);
        parser.parse();
        assert(false && "Expected exception for invalid token");
    } catch (const std::runtime_error& e) {
        Logger::getInstance().log(LogLevel::DEBUG, "Expected exception: ", e.what());
    }
    Logger::getInstance().log(LogLevel::INFO, "Parser tests passed!");
}
References Parser::parse().
Referenced by run_tests(), and cql::test::test_parser_standalone().
token_type_to_string()
std::string token_type_to_string (TokenType type)
Definition at line 301 of file cql.cpp.
{
    switch (type) {
        case TokenType::LANGUAGE: return "LANGUAGE";
        case TokenType::DESCRIPTION: return "DESCRIPTION";
        case TokenType::CONTEXT: return "CONTEXT";
        case TokenType::TEST: return "TEST";
        case TokenType::DEPENDENCY: return "DEPENDENCY";
        case TokenType::PERFORMANCE: return "PERFORMANCE";
        case TokenType::COPYRIGHT: return "COPYRIGHT";
        case TokenType::IDENTIFIER: return "IDENTIFIER";
        case TokenType::STRING: return "STRING";
        case TokenType::NEWLINE: return "NEWLINE";
        case TokenType::END: return "END";
        default: return "UNKNOWN";
    }
}
References CONTEXT, COPYRIGHT, DEPENDENCY, DESCRIPTION, END, IDENTIFIER, LANGUAGE, NEWLINE, PERFORMANCE, STRING, and TEST.
Referenced by Parser::parse_string(), and Token::to_string().
write_file()
void write_file (const std::string & filepath, const std::string & content)
Definition at line 644 of file cql.cpp.
{
    std::ofstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open file for writing: " + filepath);
    }
    file << content;
}