Claude Query Language: cql Namespace Reference
cql Namespace Reference
Namespaces
namespace cli
namespace test
namespace util
Functions
std::string token_type_to_string (TokenType type)
std::string pattern_layer_to_string (PatternLayer layer)
PatternLayer string_to_pattern_layer (const std::string &layer_str)
bool save_generated_file (const GeneratedFile &file, const std::string &directory, const Config &config)
TokenType get_node_type (const QueryNode *node)
Function Documentation
get_node_type()
TokenType cql::get_node_type (const QueryNode * node)
Definition at line 13 of file validator.cpp.
{
    if (dynamic_cast<const CodeRequestNode*>(node)) {
        // coderequestnode represents both language and description
        // for validation, we need to count it as both
        return TokenType::LANGUAGE; // we'll handle description separately
    }
    if (dynamic_cast<const ContextNode*>(node)) return TokenType::CONTEXT;
    if (dynamic_cast<const TestNode*>(node)) return TokenType::TEST;
    if (dynamic_cast<const DependencyNode*>(node)) return TokenType::DEPENDENCY;
    if (dynamic_cast<const PerformanceNode*>(node)) return TokenType::PERFORMANCE;
    if (dynamic_cast<const CopyrightNode*>(node)) return TokenType::COPYRIGHT;
    if (dynamic_cast<const ArchitectureNode*>(node)) return TokenType::ARCHITECTURE;
    if (dynamic_cast<const ConstraintNode*>(node)) return TokenType::CONSTRAINT;
    if (dynamic_cast<const ExampleNode*>(node)) return TokenType::EXAMPLE;
    if (dynamic_cast<const SecurityNode*>(node)) return TokenType::SECURITY;
    if (dynamic_cast<const ComplexityNode*>(node)) return TokenType::COMPLEXITY;
    if (dynamic_cast<const ModelNode*>(node)) return TokenType::MODEL;
    if (dynamic_cast<const FormatNode*>(node)) return TokenType::FORMAT;
    if (dynamic_cast<const VariableNode*>(node)) return TokenType::VARIABLE;
    // default fallback
    return TokenType::IDENTIFIER;
}
References CONTEXT, COPYRIGHT, DEPENDENCY, IDENTIFIER, LANGUAGE, PERFORMANCE, and TEST.
pattern_layer_to_string()
std::string cql::pattern_layer_to_string (PatternLayer layer)
Definition at line 90 of file nodes.cpp.
{
    switch (layer) {
        case PatternLayer::FOUNDATION: return "foundation";
        case PatternLayer::COMPONENT: return "component";
        case PatternLayer::INTERACTION: return "interaction";
        default: return "unknown";
    }
}
References pattern_layer_to_string().
Referenced by pattern_layer_to_string(), and cql::test::test_architecture_patterns().
save_generated_file()
bool cql::save_generated_file (const GeneratedFile & file, const std::string & directory, const Config & config)
Definition at line 451 of file response_processor.cpp.
{
    Logger::getInstance().log(LogLevel::INFO, "Saving generated file: ", file.m_filename);
    // Resolve a full path
    std::string full_path = directory.empty() ? file.m_filename : directory + "/" + file.m_filename;
    // Check if the file exists
    bool file_exists = std::filesystem::exists(full_path);
    if (file_exists && !config.should_overwrite_existing_files()) {
        Logger::getInstance().log(LogLevel::NORMAL, "File already exists and overwrite is disabled: ", full_path);
        // Create a backup or versioned filename
        std::string backup_path = full_path + ".new";
        cql::util::write_file(backup_path, file.m_content);
        Logger::getInstance().log(LogLevel::INFO, "Saved to alternative location: ", backup_path);
        return true;
    }
    // Ensure directory exists
    std::string dir_path = std::filesystem::path(full_path).parent_path().string();
    if (!dir_path.empty() && !std::filesystem::exists(dir_path)) {
        if (config.should_create_missing_directories()) {
            try {
                std::filesystem::create_directories(dir_path);
                Logger::getInstance().log(LogLevel::INFO, "Created directory: ", dir_path);
            } catch (const std::exception& e) {
                Logger::getInstance().log(LogLevel::ERROR, "Failed to create directory: ", e.what());
                return false;
            }
        } else {
            Logger::getInstance().log(LogLevel::ERROR, "Directory does not exist and creation is disabled: ", dir_path);
            return false;
        }
    }
    // Write the file
    try {
        cql::util::write_file(full_path, file.m_content);
        Logger::getInstance().log(LogLevel::INFO, "File saved successfully: ", full_path);
        return true;
    } catch (const std::exception& e) {
        Logger::getInstance().log(LogLevel::ERROR, "Failed to write file: ", e.what());
        return false;
    }
}
References save_generated_file(), and cql::util::write_file().
Referenced by save_generated_file(), cql::cli::save_generated_files(), and cql::test::test_api_integration().
string_to_pattern_layer()
PatternLayer cql::string_to_pattern_layer (const std::string & layer_str)
Definition at line 99 of file nodes.cpp.
{
    // Convert to lowercase for consistent comparison
    std::string lowercase_layer = layer_str;
    std::transform(lowercase_layer.begin(), lowercase_layer.end(), lowercase_layer.begin(),
                  [](unsigned char c) { return std::tolower(c); });
    if (lowercase_layer == "foundation") {
        return PatternLayer::FOUNDATION;
    } else if (lowercase_layer == "interaction") {
        return PatternLayer::INTERACTION;
    } else {
        // Default to component for anything else
        return PatternLayer::COMPONENT;
    }
}
References string_to_pattern_layer().
Referenced by string_to_pattern_layer(), and cql::test::test_architecture_patterns().
token_type_to_string()
std::string cql::token_type_to_string (TokenType type)
Definition at line 10 of file lexer.cpp.
{
    switch (type) {
        case TokenType::LANGUAGE: return "LANGUAGE";
        case TokenType::DESCRIPTION: return "DESCRIPTION";
        case TokenType::CONTEXT: return "CONTEXT";
        case TokenType::TEST: return "TEST";
        case TokenType::DEPENDENCY: return "DEPENDENCY";
        case TokenType::PERFORMANCE: return "PERFORMANCE";
        case TokenType::COPYRIGHT: return "COPYRIGHT";
        case TokenType::ARCHITECTURE: return "ARCHITECTURE";
        case TokenType::CONSTRAINT: return "CONSTRAINT";
        case TokenType::EXAMPLE: return "EXAMPLE";
        case TokenType::SECURITY: return "SECURITY";
        case TokenType::COMPLEXITY: return "COMPLEXITY";
        case TokenType::MODEL: return "MODEL";
        case TokenType::FORMAT: return "FORMAT";
        case TokenType::VARIABLE: return "VARIABLE";
        case TokenType::IDENTIFIER: return "IDENTIFIER";
        case TokenType::STRING: return "STRING";
        case TokenType::NEWLINE: return "NEWLINE";
        case TokenType::END: return "END";
        default: return "UNKNOWN";
    }
}
References CONTEXT, COPYRIGHT, DEPENDENCY, DESCRIPTION, END, IDENTIFIER, LANGUAGE, NEWLINE, PERFORMANCE, STRING, and TEST.