Claude Query Language: cql::util Namespace Reference
cql::util Namespace Reference
Functions
std::string read_file (const std::string &filepath)
void write_file (const std::string &filepath, const std::string &content)
bool contains (const std::string &str, const std::string &substr)
std::vector< std::vector< std::string > > extract_regex_matches (const std::string &content, const std::string &pattern, size_t expected_groups)
std::set< std::string > extract_regex_group_values (const std::string &content, const std::string &pattern, size_t group_index)
Function Documentation
contains()
bool cql::util::contains (const std::string & str, const std::string & substr)
Definition at line 31 of file util.cpp.
{
    return str.find(substr) != std::string::npos;
}
extract_regex_group_values()
std::set< std::string > cql::util::extract_regex_group_values (const std::string & content, const std::string & pattern, size_t group_index)
Definition at line 68 of file util.cpp.
  {
    std::set<std::string> values;
    std::regex regex_pattern(pattern);
    auto begin = std::sregex_iterator(content.begin(), content.end(), regex_pattern);
    auto end = std::sregex_iterator();
    for (std::sregex_iterator it = begin; it != end; ++it) {
        std::smatch match = *it;
        if (match.size() > group_index) {
            values.insert(match[group_index].str());
        }
    }
    return values;
}
extract_regex_matches()
std::vector< std::vector< std::string > > cql::util::extract_regex_matches (const std::string & content, const std::string & pattern, size_t expected_groups)
Definition at line 36 of file util.cpp.
  {
    std::vector<std::vector<std::string>> results;
    std::regex regex_pattern(pattern);
    auto begin = std::sregex_iterator(content.begin(), content.end(), regex_pattern);
    auto end = std::sregex_iterator();
    for (std::sregex_iterator it = begin; it != end; ++it) {
        std::smatch match = *it;
        // skip if we don't have the expected number of groups
        if (expected_groups > 0 && match.size() <= expected_groups) {
            continue;
        }
        // each match has multiple groups
        std::vector<std::string> groups;
        for (size_t i = 0; i < match.size(); ++i) {
            groups.push_back(match[i].str());
        }
        results.push_back(groups);
    }
    return results;
}
read_file()
std::string cql::util::read_file (const std::string & filepath)
Definition at line 15 of file util.cpp.
{
    std::ifstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open file: " + filepath);
    }
    return {std::istreambuf_iterator<char>(file), std::istreambuf_iterator<char>()};
}
Referenced by cql::cli::compile_query_for_api(), cql::cli::run_interactive(), and cql::test::test_examples_compilation().
write_file()
void cql::util::write_file (const std::string & filepath, const std::string & content)
Definition at line 23 of file util.cpp.
{
    std::ofstream file(filepath);
    if (!file.is_open()) {
        throw std::runtime_error("Failed to open file for writing: " + filepath);
    }
    file << content;
}
Referenced by cql::cli::process_file(), and cql::save_generated_file().