Claude Query Language: cql::ApiClient::Impl Struct Reference
cql::ApiClient::Impl Struct Reference
Public Member Functions
Impl (const Config &config)
~Impl ()
struct curl_slist * prepare_request (const std::string &query, std::string &request_data)
CURLcode execute_request (struct curl_slist *headers) const
ApiResponse process_response (CURLcode curl_result, const ApiResponse &partial_response)
ApiResponse process_successful_response (ApiResponse &response)
ApiResponse process_rate_limited_response (ApiResponse &response)
ApiResponse process_error_response (ApiResponse &response, long status_code)
ApiResponse send_request (const std::string &query)
Static Public Member Functions
static size_t write_callback (void *contents, size_t size, size_t nmemb, std::string *buffer)
Public Attributes
Config m_config
Client configuration.
ApiClientStatus m_status
Current client status.
std::string m_last_error
Last error message.
CURL * m_curl
CURL handle.
std::string m_response_buffer
Buffer for response data.
bool m_initialized
Whether the client is initialized.
Detailed Description
Definition at line 18 of file api_client.cpp.
Constructor & Destructor Documentation
Impl()
cql::ApiClient::Impl::Impl (const Config & config) inline explicit
Definition at line 26 of file api_client.cpp.
        : m_config(config),
          m_status(ApiClientStatus::Ready),
          m_curl(nullptr),
          m_initialized(false) {
        // Initialize CURL
        curl_global_init(CURL_GLOBAL_ALL);
        m_curl = curl_easy_init();
        if (m_curl) {
            m_initialized = true;
            Logger::getInstance().log(LogLevel::INFO, "ApiClient initialized with model: ", config.get_model());
        } else {
            m_status = ApiClientStatus::Error;
            m_last_error = "Failed to initialize CURL";
            Logger::getInstance().log(LogLevel::ERROR, "Failed to initialize CURL");
        }
    }
References m_config, m_curl, m_initialized, m_last_error, and m_status.
~Impl()
cql::ApiClient::Impl::~Impl () inline
Definition at line 46 of file api_client.cpp.
            {
        // Clean up CURL
        if (m_curl) {
            curl_easy_cleanup(m_curl);
        }
        curl_global_cleanup();
    }
References m_curl.
Member Function Documentation
execute_request()
CURLcode cql::ApiClient::Impl::execute_request (struct curl_slist * headers) const inline
Definition at line 99 of file api_client.cpp.
{
        // Perform the request
        Logger::getInstance().log(LogLevel::INFO, "Sending request to Claude API...");
        CURLcode res = curl_easy_perform(m_curl);
        // Cleanup headers
        curl_slist_free_all(headers);
        return res;
    }
References m_curl.
Referenced by send_request().
prepare_request()
struct curl_slist * cql::ApiClient::Impl::prepare_request (const std::string & query, std::string & request_data) inline
Definition at line 62 of file api_client.cpp.
{
        // Construct the request JSON
        nlohmann::json request_json = {
            {"model", m_config.get_model()},
            {"max_tokens", 100000},
            {"messages", {
                {
                    {"role", "user"},
                    {"content", query}
                }
            }}
        };
        request_data = request_json.dump();
        // Construct the full URL by combining base URL and endpoint
        std::string api_url = m_config.get_api_base_url() + "/v1/messages";
        // Set up CURL request
        curl_easy_setopt(m_curl, CURLOPT_URL, api_url.c_str());
        curl_easy_setopt(m_curl, CURLOPT_WRITEFUNCTION, write_callback);
        curl_easy_setopt(m_curl, CURLOPT_WRITEDATA, &m_response_buffer);
        curl_easy_setopt(m_curl, CURLOPT_POSTFIELDS, request_data.c_str());
        curl_easy_setopt(m_curl, CURLOPT_TIMEOUT, m_config.get_timeout());
        // Set headers
        struct curl_slist* headers = nullptr;
        headers = curl_slist_append(headers, "Content-Type: application/json");
        std::string auth_header = "x-api-key: " + m_config.get_api_key();
        headers = curl_slist_append(headers, auth_header.c_str());
        headers = curl_slist_append(headers, "anthropic-version: 2023-06-01");
        curl_easy_setopt(m_curl, CURLOPT_HTTPHEADER, headers);
        return headers;
    }
References m_config, m_curl, m_response_buffer, and write_callback().
Referenced by send_request().
process_error_response()
ApiResponse cql::ApiClient::Impl::process_error_response (ApiResponse & response, long status_code) inline
Definition at line 176 of file api_client.cpp.
{
        m_status = ApiClientStatus::Error;
        try {
            // Try to parse error from JSON
            nlohmann::json json_response = nlohmann::json::parse(m_response_buffer);
            if (json_response.contains("error") && json_response["error"].is_object()) {
                auto error = json_response["error"];
                if (error.contains("message") && error["message"].is_string()) {
                    m_last_error = error["message"];
                }
            }
        } catch (...) {
            // If parsing fails, use the raw response as error
            m_last_error = "API error " + std::to_string(status_code) + ": " + m_response_buffer;
        }
        response.m_error_message = m_last_error;
        Logger::getInstance().log(LogLevel::ERROR, "API error (", status_code, "): ", m_last_error);
        return response;
    }
References m_last_error, m_response_buffer, and m_status.
Referenced by process_response().
process_rate_limited_response()
ApiResponse cql::ApiClient::Impl::process_rate_limited_response (ApiResponse & response) inline
Definition at line 168 of file api_client.cpp.
{
        m_status = ApiClientStatus::RateLimited;
        response.m_error_message = "Rate limited: Too many requests";
        Logger::getInstance().log(LogLevel::ERROR, "API rate limit exceeded (429)");
        return response;
    }
References m_status.
Referenced by process_response().
process_response()
ApiResponse cql::ApiClient::Impl::process_response (CURLcode curl_result, const ApiResponse & partial_response) inline
Definition at line 111 of file api_client.cpp.
{
        ApiResponse response = partial_response;
        // Check for CURL errors
        if (curl_result != CURLE_OK) {
            m_status = ApiClientStatus::Error;
            m_last_error = curl_easy_strerror(curl_result);
            response.m_error_message = m_last_error;
            response.m_status_code = 0;
            Logger::getInstance().log(LogLevel::ERROR, "CURL error: ", m_last_error);
            return response;
        }
        // Get status code
        long status_code;
        curl_easy_getinfo(m_curl, CURLINFO_RESPONSE_CODE, &status_code);
        response.m_status_code = static_cast<int>(status_code);
        // Process response based on status code
        if (status_code >= 200 && status_code < 300) {
            return process_successful_response(response);
        } else if (status_code == 429) {
            return process_rate_limited_response(response);
        } else {
            return process_error_response(response, status_code);
        }
    }
References m_curl, m_last_error, m_status, process_error_response(), process_rate_limited_response(), and process_successful_response().
Referenced by send_request().
process_successful_response()
ApiResponse cql::ApiClient::Impl::process_successful_response (ApiResponse & response) inline
Definition at line 140 of file api_client.cpp.
{
        m_status = ApiClientStatus::Ready;
        response.m_success = true;
        response.m_raw_response = m_response_buffer;
        try {
            // Parse JSON response
            nlohmann::json json_response = nlohmann::json::parse(m_response_buffer);
            if (json_response.contains("content") && json_response["content"].is_array()) {
                // Extract content from response
                for (const auto& content : json_response["content"]) {
                    if (content.contains("text") && content["text"].is_string()) {
                        response.m_raw_response = content["text"];
                        break;
                    }
                }
            }
            Logger::getInstance().log(LogLevel::INFO, "API request successful");
        } catch (const std::exception& e) {
            Logger::getInstance().log(LogLevel::ERROR, "Error parsing API response: ", e.what());
            // Still mark as success since we got a valid HTTP response,
            // The response processor will handle extracting code blocks
        }
        return response;
    }
References m_response_buffer, and m_status.
Referenced by process_response().
send_request()
ApiResponse cql::ApiClient::Impl::send_request (const std::string & query) inline
Definition at line 199 of file api_client.cpp.
{
        if (!m_initialized) {
            ApiResponse response;
            response.m_success = false;
            response.m_status_code = 0;
            response.m_error_message = "CURL not initialized";
            return response;
        }
        // Reset response buffer
        m_response_buffer.clear();
        // Set client status
        m_status = ApiClientStatus::Processing;
        // Prepare request
        std::string request_data;
        struct curl_slist* headers = prepare_request(query, request_data);
        // Prepare response
        ApiResponse response;
        response.m_success = false;
        // Execute request
        CURLcode curl_result = execute_request(headers);
        // Process response
        return process_response(curl_result, response);
    }
References execute_request(), m_initialized, m_response_buffer, m_status, prepare_request(), and process_response().
write_callback()
static size_t cql::ApiClient::Impl::write_callback (void * contents, size_t size, size_t nmemb, std::string * buffer) inline static
Definition at line 55 of file api_client.cpp.
{
        size_t real_size = size * nmemb;
        buffer->append(static_cast<char*>(contents), real_size);
        return real_size;
    }
Referenced by prepare_request().
Member Data Documentation
m_config
Config cql::ApiClient::Impl::m_config
Client configuration.
Definition at line 19 of file api_client.cpp.
Referenced by Impl(), and prepare_request().
m_curl
CURL* cql::ApiClient::Impl::m_curl
CURL handle.
Definition at line 22 of file api_client.cpp.
Referenced by execute_request(), Impl(), prepare_request(), process_response(), and ~Impl().
m_initialized
bool cql::ApiClient::Impl::m_initialized
Whether the client is initialized.
Definition at line 24 of file api_client.cpp.
Referenced by Impl(), and send_request().
m_last_error
std::string cql::ApiClient::Impl::m_last_error
Last error message.
Definition at line 21 of file api_client.cpp.
Referenced by Impl(), process_error_response(), and process_response().
m_response_buffer
std::string cql::ApiClient::Impl::m_response_buffer
Buffer for response data.
Definition at line 23 of file api_client.cpp.
Referenced by prepare_request(), process_error_response(), process_successful_response(), and send_request().
m_status
ApiClientStatus cql::ApiClient::Impl::m_status
Current client status.
Definition at line 20 of file api_client.cpp.
Referenced by Impl(), process_error_response(), process_rate_limited_response(), process_response(), process_successful_response(), and send_request().
The documentation for this struct was generated from the following file:
src/cql/api_client.cpp