Document Processing System: doc_system::Microservice Class Reference
doc_system::Microservice Class Reference abstract
#include <message_queue.h>
Public Member Functions
Microservice (const std::string &name)
virtual ~Microservice ()
void start ()
void stop ()
std::string getName () const
Protected Member Functions
virtual void initialize ()=0
virtual void run ()=0
template<typename T>
void subscribe (const std::string &topic, std::function< void(T)> callback)
template<typename T>
void publish (const std::string &topic, T &&payload)
Protected Attributes
std::string name_
std::atomic< bool > running_
std::thread serviceThread_
Detailed Description
Definition at line 192 of file message_queue.h.
Constructor & Destructor Documentation
Microservice()
doc_system::Microservice::Microservice (const std::string & name) inline
Definition at line 194 of file message_queue.h.
: name_(name), running_(false) {}
References name_, and running_.
Referenced by doc_system::DocumentProcessingService::DocumentProcessingService().
~Microservice()
virtual doc_system::Microservice::~Microservice () inline virtual
Definition at line 196 of file message_queue.h.
{
        stop();
    }
References stop().
Member Function Documentation
getName()
std::string doc_system::Microservice::getName () const inline
Definition at line 230 of file message_queue.h.
{
        return name_;
    }
References name_.
initialize()
virtual void doc_system::Microservice::initialize () protected pure virtual
Implemented in doc_system::DocumentProcessingService.
Referenced by start().
publish()
template<typename T> void doc_system::Microservice::publish (const std::string & topic, T && payload) inline protected
Definition at line 249 of file message_queue.h.
{
        MessageQueue::getInstance().publish(topic, std::forward<T>(payload));
    }
References doc_system::MessageQueue::getInstance(), and doc_system::MessageQueue::publish().
Referenced by doc_system::DocumentProcessingService::processDocument().
run()
virtual void doc_system::Microservice::run () protected pure virtual
Implemented in doc_system::DocumentProcessingService.
Referenced by start().
start()
void doc_system::Microservice::start () inline
Definition at line 201 of file message_queue.h.
                 {
        if (running_) {
            return;
        }
        running_ = true;
        // Start message processing
        MessageQueue::getInstance().startProcessing();
        // Initialize the service
        initialize();
        // Start the service thread
        serviceThread_ = std::thread([this]() {
            this->run();
        });
    }
References doc_system::MessageQueue::getInstance(), initialize(), run(), running_, serviceThread_, and doc_system::MessageQueue::startProcessing().
Referenced by main().
stop()
void doc_system::Microservice::stop () inline
Definition at line 221 of file message_queue.h.
                {
        running_ = false;
        if (serviceThread_.joinable()) {
            serviceThread_.join();
        }
    }
References running_, and serviceThread_.
Referenced by main(), and ~Microservice().
subscribe()
template<typename T> void doc_system::Microservice::subscribe (const std::string & topic, std::function< void(T)> callback) inline protected
Definition at line 243 of file message_queue.h.
{
        MessageQueue::getInstance().subscribe<T>(topic, std::move(callback));
    }
References doc_system::MessageQueue::getInstance(), and doc_system::MessageQueue::subscribe().
Referenced by doc_system::DocumentProcessingService::initialize().
Member Data Documentation
name_
std::string doc_system::Microservice::name_ protected
Definition at line 253 of file message_queue.h.
Referenced by getName(), and Microservice().
running_
std::atomic<bool> doc_system::Microservice::running_ protected
Definition at line 254 of file message_queue.h.
Referenced by Microservice(), doc_system::DocumentProcessingService::run(), start(), and stop().
serviceThread_
std::thread doc_system::Microservice::serviceThread_ protected
Definition at line 255 of file message_queue.h.
Referenced by start(), and stop().
The documentation for this class was generated from the following file:
headers/message_queue.h