Document Processing System: doc_system::DocumentManager Class Reference
doc_system::DocumentManager Class Reference
#include <document_manager.h>
Public Member Functions
DocumentManager (const DocumentManager &)=delete
DocumentManager & operator= (const DocumentManager &)=delete
DocumentManager (DocumentManager &&)=delete
DocumentManager & operator= (DocumentManager &&)=delete
void registerDocument (DocumentPtr document)
DocumentPtr getDocument (const std::string &filename)
bool unregisterDocument (const std::string &filename)
std::vector< DocumentPtr > getAllDocuments ()
size_t getDocumentCount () const
Static Public Member Functions
static DocumentManager & getInstance ()
Private Member Functions
DocumentManager ()=default
Private Attributes
std::mutex mutex_
std::unordered_map< std::string, DocumentPtr > documents_
Detailed Description
Definition at line 15 of file document_manager.h.
Constructor & Destructor Documentation
DocumentManager() [1/3]
doc_system::DocumentManager::DocumentManager (const DocumentManager &) delete
References DocumentManager().
Referenced by DocumentManager(), DocumentManager(), getInstance(), operator=(), and operator=().
DocumentManager() [2/3]
doc_system::DocumentManager::DocumentManager (DocumentManager &&) delete
References DocumentManager().
DocumentManager() [3/3]
doc_system::DocumentManager::DocumentManager () private default
Member Function Documentation
getAllDocuments()
std::vector< DocumentPtr > doc_system::DocumentManager::getAllDocuments () inline
Definition at line 57 of file document_manager.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        std::vector<DocumentPtr> result;
        result.reserve(documents_.size());
        for (const auto& [_, doc] : documents_) {
            result.push_back(doc);
        }
        return result;
    }
References documents_, and mutex_.
getDocument()
DocumentPtr doc_system::DocumentManager::getDocument (const std::string & filename) inline
Definition at line 41 of file document_manager.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        auto it = documents_.find(filename);
        if (it != documents_.end()) {
            return it->second;
        }
        return nullptr;
    }
References documents_, and mutex_.
getDocumentCount()
size_t doc_system::DocumentManager::getDocumentCount () const inline
Definition at line 70 of file document_manager.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return documents_.size();
    }
References documents_, and mutex_.
Referenced by main().
getInstance()
static DocumentManager & doc_system::DocumentManager::getInstance () inline static
Definition at line 24 of file document_manager.h.
{
        static DocumentManager instance;  // C++11 guarantees thread-safe initialization
        return instance;
    }
References DocumentManager().
Referenced by main(), SingletonTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
operator=() [1/2]
DocumentManager & doc_system::DocumentManager::operator= (const DocumentManager &) delete
References DocumentManager().
operator=() [2/2]
DocumentManager & doc_system::DocumentManager::operator= (DocumentManager &&) delete
References DocumentManager().
registerDocument()
void doc_system::DocumentManager::registerDocument (DocumentPtr document) inline
Definition at line 30 of file document_manager.h.
{
        if (!document) {
            throw std::invalid_argument("Cannot register a null document");
        }
        std::lock_guard<std::mutex> lock(mutex_);
        const std::string& filename = document->getFilename();
        documents_[filename] = document;
    }
References documents_, and mutex_.
Referenced by main().
unregisterDocument()
bool doc_system::DocumentManager::unregisterDocument (const std::string & filename) inline
Definition at line 51 of file document_manager.h.
{
        std::lock_guard<std::mutex> lock(mutex_);
        return documents_.erase(filename) > 0;
    }
References documents_, and mutex_.
Member Data Documentation
documents_
std::unordered_map<std::string, DocumentPtr> doc_system::DocumentManager::documents_ private
Definition at line 83 of file document_manager.h.
Referenced by getAllDocuments(), getDocument(), getDocumentCount(), registerDocument(), and unregisterDocument().
mutex_
std::mutex doc_system::DocumentManager::mutex_ mutable private
Definition at line 80 of file document_manager.h.
Referenced by getAllDocuments(), getDocument(), getDocumentCount(), registerDocument(), and unregisterDocument().
The documentation for this class was generated from the following file:
headers/document_manager.h