Document Processing System: doc_system::ToolFactory Class Reference
doc_system::ToolFactory Class Reference
#include <abstract_factory.h>
Static Public Member Functions
static std::tuple< ViewerPtr, EditorPtr, ConverterPtr > createToolsFor (DocumentType type)
Detailed Description
Definition at line 89 of file abstract_factory.h.
Member Function Documentation
createToolsFor()
static std::tuple< ViewerPtr, EditorPtr, ConverterPtr > doc_system::ToolFactory::createToolsFor (DocumentType type) inline static
Definition at line 92 of file abstract_factory.h.
{
        auto factory = DocumentToolFactory::createFactory(type);
        return std::make_tuple(
            factory->createViewer(),
            factory->createEditor(),
            factory->createConverter()
        );
    }
References doc_system::DocumentToolFactory::createFactory().
Referenced by main(), and TEST_F().
The documentation for this class was generated from the following file:
headers/abstract_factory.h