Document Processing System: doc_system::DocumentBuilder Class Reference
doc_system::DocumentBuilder Class Reference
#include <document_builder.h>
Public Member Functions
DocumentBuilder ()=default
void reset (DocumentPtr document)
DocumentBuilder & buildHeader (const std::string &header)
DocumentBuilder & buildContent (const std::string &content)
DocumentBuilder & buildFooter (const std::string &footer)
DocumentBuilder & buildMetadata (const MetadataMap &metadata)
DocumentPtr getDocument () const
const std::vector< std::string > & getBuildSteps () const
Private Attributes
DocumentPtr document_
std::vector< std::string > buildSteps_
Detailed Description
Definition at line 11 of file document_builder.h.
Constructor & Destructor Documentation
DocumentBuilder()
doc_system::DocumentBuilder::DocumentBuilder () default
Referenced by buildContent(), buildFooter(), buildHeader(), and buildMetadata().
Member Function Documentation
buildContent()
DocumentBuilder & doc_system::DocumentBuilder::buildContent (const std::string & content) inline
Definition at line 30 of file document_builder.h.
{
        if (document_) {
            document_->setContent(content);
            buildSteps_.push_back("Content");
        }
        return *this;
    }
References buildSteps_, document_, and DocumentBuilder().
Referenced by doc_system::DocumentDirector::buildBusinessDocument(), doc_system::DocumentDirector::buildMinimalDocument(), doc_system::DocumentDirector::buildStandardDocument(), main(), and TEST_F().
buildFooter()
DocumentBuilder & doc_system::DocumentBuilder::buildFooter (const std::string & footer) inline
Definition at line 38 of file document_builder.h.
{
        if (document_) {
            document_->setFooter(footer);
            buildSteps_.push_back("Footer");
        }
        return *this;
    }
References buildSteps_, document_, and DocumentBuilder().
Referenced by doc_system::DocumentDirector::buildStandardDocument(), main(), and TEST_F().
buildHeader()
DocumentBuilder & doc_system::DocumentBuilder::buildHeader (const std::string & header) inline
Definition at line 22 of file document_builder.h.
{
        if (document_) {
            document_->setHeader(header);
            buildSteps_.push_back("Header");
        }
        return *this;
    }
References buildSteps_, document_, and DocumentBuilder().
Referenced by doc_system::DocumentDirector::buildBusinessDocument(), doc_system::DocumentDirector::buildStandardDocument(), main(), and TEST_F().
buildMetadata()
DocumentBuilder & doc_system::DocumentBuilder::buildMetadata (const MetadataMap & metadata) inline
Definition at line 46 of file document_builder.h.
{
        if (document_) {
            document_->setMetadata(metadata);
            buildSteps_.push_back("Metadata");
        }
        return *this;
    }
References buildSteps_, document_, and DocumentBuilder().
Referenced by doc_system::DocumentDirector::buildBusinessDocument(), doc_system::DocumentDirector::buildStandardDocument(), and main().
getBuildSteps()
const std::vector< std::string > & doc_system::DocumentBuilder::getBuildSteps () const inline
Definition at line 60 of file document_builder.h.
{
        return buildSteps_;
    }
References buildSteps_.
Referenced by TEST_F(), TEST_F(), TEST_F(), and TEST_F().
getDocument()
DocumentPtr doc_system::DocumentBuilder::getDocument () const inline
Definition at line 55 of file document_builder.h.
{
        return document_;
    }
References document_.
Referenced by main().
reset()
void doc_system::DocumentBuilder::reset (DocumentPtr document) inline
Definition at line 16 of file document_builder.h.
{
        document_ = document;
        buildSteps_.clear();
    }
References buildSteps_, and document_.
Referenced by main(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
Member Data Documentation
buildSteps_
std::vector<std::string> doc_system::DocumentBuilder::buildSteps_ private
Definition at line 66 of file document_builder.h.
Referenced by buildContent(), buildFooter(), buildHeader(), buildMetadata(), getBuildSteps(), and reset().
document_
DocumentPtr doc_system::DocumentBuilder::document_ private
Definition at line 65 of file document_builder.h.
Referenced by buildContent(), buildFooter(), buildHeader(), buildMetadata(), getDocument(), and reset().
The documentation for this class was generated from the following file:
headers/document_builder.h