Document Processing System: doc_system::DocumentToolFactory Class Reference
doc_system::DocumentToolFactory Class Reference abstract
#include <abstract_factory.h>
Public Member Functions
virtual ~DocumentToolFactory ()=default
virtual ViewerPtr createViewer () const =0
virtual EditorPtr createEditor () const =0
virtual ConverterPtr createConverter () const =0
Static Public Member Functions
static std::unique_ptr< DocumentToolFactory > createFactory (DocumentType type)
Detailed Description
Definition at line 49 of file abstract_factory.h.
Constructor & Destructor Documentation
~DocumentToolFactory()
virtual doc_system::DocumentToolFactory::~DocumentToolFactory () virtual default
Member Function Documentation
createConverter()
virtual ConverterPtr doc_system::DocumentToolFactory::createConverter () const pure virtual
Implemented in doc_system::PdfToolFactory, doc_system::TextToolFactory, and doc_system::WordToolFactory.
createEditor()
virtual EditorPtr doc_system::DocumentToolFactory::createEditor () const pure virtual
Implemented in doc_system::PdfToolFactory, doc_system::TextToolFactory, and doc_system::WordToolFactory.
createFactory()
std::unique_ptr< DocumentToolFactory > doc_system::DocumentToolFactory::createFactory (DocumentType type) static
Definition at line 7 of file abstract_factory.cpp.
{
    switch (type) {
        case DocumentType::PDF:
            return std::make_unique<PdfToolFactory>();
        case DocumentType::Word:
            return std::make_unique<WordToolFactory>();
        case DocumentType::Text:
            return std::make_unique<TextToolFactory>();
        default:
            throw std::invalid_argument("Unsupported document type");
    }
}
References doc_system::PDF, doc_system::Text, and doc_system::Word.
Referenced by doc_system::ToolFactory::createToolsFor(), TEST_F(), TEST_F(), and TEST_F().
createViewer()
virtual ViewerPtr doc_system::DocumentToolFactory::createViewer () const pure virtual
Implemented in doc_system::PdfToolFactory, doc_system::TextToolFactory, and doc_system::WordToolFactory.
The documentation for this class was generated from the following files:
headers/abstract_factory.h
src/abstract_factory.cpp