Document Processing System: doc_system::DocumentDirector Class Reference
doc_system::DocumentDirector Class Reference
#include <document_builder.h>
Static Public Member Functions
static void buildStandardDocument (DocumentBuilder &builder, const std::string &header, const std::string &content, const std::string &footer, const MetadataMap &metadata)
static void buildMinimalDocument (DocumentBuilder &builder, const std::string &content)
static void buildBusinessDocument (DocumentBuilder &builder, const std::string &header, const std::string &content, const MetadataMap &metadata)
Detailed Description
Definition at line 70 of file document_builder.h.
Member Function Documentation
buildBusinessDocument()
static void doc_system::DocumentDirector::buildBusinessDocument (DocumentBuilder & builder, const std::string & header, const std::string & content, const MetadataMap & metadata) inline static
Definition at line 91 of file document_builder.h.
{
        builder.buildMetadata(metadata)
               .buildHeader(header)
               .buildContent(content);
    }
References doc_system::DocumentBuilder::buildContent(), doc_system::DocumentBuilder::buildHeader(), and doc_system::DocumentBuilder::buildMetadata().
Referenced by TEST_F().
buildMinimalDocument()
static void doc_system::DocumentDirector::buildMinimalDocument (DocumentBuilder & builder, const std::string & content) inline static
Definition at line 85 of file document_builder.h.
{
        builder.buildContent(content);
    }
References doc_system::DocumentBuilder::buildContent().
Referenced by TEST_F().
buildStandardDocument()
static void doc_system::DocumentDirector::buildStandardDocument (DocumentBuilder & builder, const std::string & header, const std::string & content, const std::string & footer, const MetadataMap & metadata) inline static
Definition at line 73 of file document_builder.h.
{
        builder.buildHeader(header)
               .buildContent(content)
               .buildFooter(footer)
               .buildMetadata(metadata);
    }
References doc_system::DocumentBuilder::buildContent(), doc_system::DocumentBuilder::buildFooter(), doc_system::DocumentBuilder::buildHeader(), and doc_system::DocumentBuilder::buildMetadata().
Referenced by TEST_F().
The documentation for this class was generated from the following file:
headers/document_builder.h