Document Processing System: doc_system::DocumentFactory Class Reference
doc_system::DocumentFactory Class Reference
#include <document_factory.h>
Static Public Member Functions
static DocumentPtr createDocument (const std::string &filename)
static DocumentPtr createPdfDocument (const std::string &filename)
static DocumentPtr createWordDocument (const std::string &filename)
static DocumentPtr createTextDocument (const std::string &filename)
Detailed Description
Definition at line 13 of file document_factory.h.
Member Function Documentation
createDocument()
static DocumentPtr doc_system::DocumentFactory::createDocument (const std::string & filename) inline static
Definition at line 16 of file document_factory.h.
{
            auto extension = std::filesystem::path(filename).extension().string();
            // Convert to lowercase for case-insensitive comparison
            std::transform(extension.begin(), extension.end(), extension.begin(),
                          [](unsigned char c) { return std::tolower(c); });
            if (extension == ".pdf") {
                return createPdfDocument(filename);
            } else if (extension == ".docx" || extension == ".doc") {
                return createWordDocument(filename);
            } else if (extension == ".txt") {
                return createTextDocument(filename);
            } else {
                throw std::invalid_argument(
                    std::format("Unsupported file extension: {}", extension));
            }
        }
References createPdfDocument(), createTextDocument(), and createWordDocument().
Referenced by main(), AbstractFactoryTest::SetUp(), BuilderTest::SetUp(), ObserverTest::SetUp(), StrategyTest::SetUp(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), TEST_F(), and TEST_F().
createPdfDocument()
static DocumentPtr doc_system::DocumentFactory::createPdfDocument (const std::string & filename) inline static
Definition at line 36 of file document_factory.h.
{
            return std::make_shared<PdfDocument>(filename);
        }
Referenced by createDocument().
createTextDocument()
static DocumentPtr doc_system::DocumentFactory::createTextDocument (const std::string & filename) inline static
Definition at line 44 of file document_factory.h.
{
            return std::make_shared<TextDocument>(filename);
        }
Referenced by createDocument().
createWordDocument()
static DocumentPtr doc_system::DocumentFactory::createWordDocument (const std::string & filename) inline static
Definition at line 40 of file document_factory.h.
{
            return std::make_shared<WordDocument>(filename);
        }
Referenced by createDocument().
The documentation for this class was generated from the following file:
headers/document_factory.h