Document Processing System: doc_system::StrategyRegistry Class Reference
doc_system::StrategyRegistry Class Reference
#include <document_strategy.h>
Public Member Functions
template<typename T>
void registerFormattingStrategy (const std::string &name)
std::unique_ptr< TextFormattingStrategy > createFormattingStrategy (const std::string &name)
template<typename T>
void registerRenderingStrategy (const std::string &name)
std::unique_ptr< ImageRenderingStrategy > createRenderingStrategy (const std::string &name)
template<typename T>
void registerLayoutStrategy (const std::string &name)
std::unique_ptr< TableLayoutStrategy > createLayoutStrategy (const std::string &name)
Static Public Member Functions
static StrategyRegistry & getInstance ()
Private Member Functions
StrategyRegistry ()
Private Attributes
std::unordered_map< std::string, std::function< std::unique_ptr< TextFormattingStrategy >()> > formattingStrategies_
std::unordered_map< std::string, std::function< std::unique_ptr< ImageRenderingStrategy >()> > renderingStrategies_
std::unordered_map< std::string, std::function< std::unique_ptr< TableLayoutStrategy >()> > layoutStrategies_
Detailed Description
Definition at line 98 of file document_strategy.h.
Constructor & Destructor Documentation
StrategyRegistry()
doc_system::StrategyRegistry::StrategyRegistry () inline private
Definition at line 164 of file document_strategy.h.
                       {
        // Register default strategies
        registerFormattingStrategy<CorporateFormattingStrategy>("corporate");
        registerFormattingStrategy<AcademicFormattingStrategy>("academic");
        registerRenderingStrategy<HighQualityRenderingStrategy>("high-quality");
        registerRenderingStrategy<FastRenderingStrategy>("fast");
        registerLayoutStrategy<GridLayoutStrategy>("grid");
        registerLayoutStrategy<CompactLayoutStrategy>("compact");
    }
References registerFormattingStrategy(), registerLayoutStrategy(), and registerRenderingStrategy().
Referenced by getInstance().
Member Function Documentation
createFormattingStrategy()
std::unique_ptr< TextFormattingStrategy > doc_system::StrategyRegistry::createFormattingStrategy (const std::string & name) inline
Definition at line 118 of file document_strategy.h.
{
        auto it = formattingStrategies_.find(name);
        if (it != formattingStrategies_.end()) {
            return it->second();
        }
        throw std::invalid_argument("Unknown formatting strategy: " + name);
    }
References formattingStrategies_.
Referenced by doc_system::TextFormattingStrategy::create().
createLayoutStrategy()
std::unique_ptr< TableLayoutStrategy > doc_system::StrategyRegistry::createLayoutStrategy (const std::string & name) inline
Definition at line 155 of file document_strategy.h.
{
        auto it = layoutStrategies_.find(name);
        if (it != layoutStrategies_.end()) {
            return it->second();
        }
        throw std::invalid_argument("Unknown layout strategy: " + name);
    }
References layoutStrategies_.
Referenced by doc_system::TableLayoutStrategy::create().
createRenderingStrategy()
std::unique_ptr< ImageRenderingStrategy > doc_system::StrategyRegistry::createRenderingStrategy (const std::string & name) inline
Definition at line 137 of file document_strategy.h.
{
        auto it = renderingStrategies_.find(name);
        if (it != renderingStrategies_.end()) {
            return it->second();
        }
        throw std::invalid_argument("Unknown rendering strategy: " + name);
    }
References renderingStrategies_.
Referenced by doc_system::ImageRenderingStrategy::create().
getInstance()
static StrategyRegistry & doc_system::StrategyRegistry::getInstance () inline static
Definition at line 101 of file document_strategy.h.
{
        static StrategyRegistry instance;
        return instance;
    }
References StrategyRegistry().
Referenced by doc_system::ImageRenderingStrategy::create(), doc_system::TableLayoutStrategy::create(), doc_system::TextFormattingStrategy::create(), and TEST_F().
registerFormattingStrategy()
template<typename T> void doc_system::StrategyRegistry::registerFormattingStrategy (const std::string & name) inline
Definition at line 108 of file document_strategy.h.
{
        static_assert(std::is_base_of<TextFormattingStrategy, T>::value,
                     "Type must derive from TextFormattingStrategy");
        formattingStrategies_[name] = []() {
            return std::make_unique<T>();
        };
    }
References formattingStrategies_.
Referenced by StrategyRegistry(), and TEST_F().
registerLayoutStrategy()
template<typename T> void doc_system::StrategyRegistry::registerLayoutStrategy (const std::string & name) inline
Definition at line 146 of file document_strategy.h.
{
        static_assert(std::is_base_of<TableLayoutStrategy, T>::value,
                     "Type must derive from TableLayoutStrategy");
        layoutStrategies_[name] = []() {
            return std::make_unique<T>();
        };
    }
References layoutStrategies_.
Referenced by StrategyRegistry().
registerRenderingStrategy()
template<typename T> void doc_system::StrategyRegistry::registerRenderingStrategy (const std::string & name) inline
Definition at line 128 of file document_strategy.h.
{
        static_assert(std::is_base_of<ImageRenderingStrategy, T>::value,
                     "Type must derive from ImageRenderingStrategy");
        renderingStrategies_[name] = []() {
            return std::make_unique<T>();
        };
    }
References renderingStrategies_.
Referenced by StrategyRegistry().
Member Data Documentation
formattingStrategies_
std::unordered_map<std::string, std::function<std::unique_ptr<TextFormattingStrategy>()> > doc_system::StrategyRegistry::formattingStrategies_ private
Definition at line 176 of file document_strategy.h.
Referenced by createFormattingStrategy(), and registerFormattingStrategy().
layoutStrategies_
std::unordered_map<std::string, std::function<std::unique_ptr<TableLayoutStrategy>()> > doc_system::StrategyRegistry::layoutStrategies_ private
Definition at line 178 of file document_strategy.h.
Referenced by createLayoutStrategy(), and registerLayoutStrategy().
renderingStrategies_
std::unordered_map<std::string, std::function<std::unique_ptr<ImageRenderingStrategy>()> > doc_system::StrategyRegistry::renderingStrategies_ private
Definition at line 177 of file document_strategy.h.
Referenced by createRenderingStrategy(), and registerRenderingStrategy().
The documentation for this class was generated from the following file:
headers/document_strategy.h