Document Processing System: doc_system::TextDocument Class Reference
doc_system::TextDocument Class Reference
#include <concrete_documents.h>
Public Member Functions
TextDocument (const std::string &filename)
DocumentType getType () const override
void save () override
void load () override
void applyFormatting (const std::string &strategyName) override
void applyRendering (const std::string &strategyName) override
void applyLayout (const std::string &strategyName) override
Public Member Functions inherited from doc_system::BaseDocument
BaseDocument (const std::string &filename)
void attachObserver (ObserverPtr observer) override
void detachObserver (ObserverPtr observer) override
void notifyObservers (const std::string &eventType) override
std::string getFilename () const override
void updateContent (const std::string &newContent) override
void setHeader (const std::string &header) override
void setContent (const std::string &content) override
void setFooter (const std::string &footer) override
void setMetadata (const MetadataMap &metadata) override
Public Member Functions inherited from doc_system::Document
virtual ~Document ()=default
Additional Inherited Members
Protected Attributes inherited from doc_system::BaseDocument
std::string filename_
std::string header_
std::string content_
std::string footer_
MetadataMap metadata_
std::vector< ObserverPtr > observers_
Detailed Description
Definition at line 86 of file concrete_documents.h.
Constructor & Destructor Documentation
TextDocument()
doc_system::TextDocument::TextDocument (const std::string & filename) inline explicit
Definition at line 88 of file concrete_documents.h.
: BaseDocument(filename) {}
References doc_system::BaseDocument::BaseDocument().
Member Function Documentation
applyFormatting()
void doc_system::TextDocument::applyFormatting (const std::string & strategyName) inline override virtual
Implements doc_system::Document.
Definition at line 104 of file concrete_documents.h.
{
        auto strategy = TextFormattingStrategy::create(strategyName);
        strategy->format(*this);
    }
References doc_system::TextFormattingStrategy::create().
applyLayout()
void doc_system::TextDocument::applyLayout (const std::string & strategyName) inline override virtual
Implements doc_system::Document.
Definition at line 114 of file concrete_documents.h.
{
        auto strategy = TableLayoutStrategy::create(strategyName);
        strategy->layout(*this);
    }
References doc_system::TableLayoutStrategy::create().
applyRendering()
void doc_system::TextDocument::applyRendering (const std::string & strategyName) inline override virtual
Implements doc_system::Document.
Definition at line 109 of file concrete_documents.h.
{
        auto strategy = ImageRenderingStrategy::create(strategyName);
        strategy->render(*this);
    }
References doc_system::ImageRenderingStrategy::create().
getType()
DocumentType doc_system::TextDocument::getType () const inline override virtual
Implements doc_system::Document.
Definition at line 90 of file concrete_documents.h.
{
        return DocumentType::Text;
    }
References doc_system::Text.
load()
void doc_system::TextDocument::load () inline override virtual
Implements doc_system::Document.
Definition at line 99 of file concrete_documents.h.
{
        std::cout << "Loading Text document: " << filename_ << std::endl;
        notifyObservers(events::DocumentLoaded);
    }
References doc_system::events::DocumentLoaded, doc_system::BaseDocument::filename_, and doc_system::BaseDocument::notifyObservers().
save()
void doc_system::TextDocument::save () inline override virtual
Implements doc_system::Document.
Definition at line 94 of file concrete_documents.h.
{
        std::cout << "Saving Text document: " << filename_ << std::endl;
        notifyObservers(events::DocumentSaved);
    }
References doc_system::events::DocumentSaved, doc_system::BaseDocument::filename_, and doc_system::BaseDocument::notifyObservers().
The documentation for this class was generated from the following file:
headers/concrete_documents.h