Document Processing System: doc_system::DocumentProcessingService Class Reference
doc_system::DocumentProcessingService Class Reference
#include <message_queue.h>
Public Member Functions
DocumentProcessingService ()
Public Member Functions inherited from doc_system::Microservice
Microservice (const std::string &name)
virtual ~Microservice ()
void start ()
void stop ()
std::string getName () const
Protected Member Functions
void initialize () override
void run () override
Protected Member Functions inherited from doc_system::Microservice
template<typename T>
void subscribe (const std::string &topic, std::function< void(T)> callback)
template<typename T>
void publish (const std::string &topic, T &&payload)
Private Member Functions
void processDocument (DocumentPtr document)
Additional Inherited Members
Protected Attributes inherited from doc_system::Microservice
std::string name_
std::atomic< bool > running_
std::thread serviceThread_
Detailed Description
Definition at line 259 of file message_queue.h.
Constructor & Destructor Documentation
DocumentProcessingService()
doc_system::DocumentProcessingService::DocumentProcessingService () inline
Definition at line 261 of file message_queue.h.
: Microservice("DocumentProcessor") {}
References doc_system::Microservice::Microservice().
Member Function Documentation
initialize()
void doc_system::DocumentProcessingService::initialize () inline override protected virtual
Implements doc_system::Microservice.
Definition at line 264 of file message_queue.h.
{
        // Subscribe to document processing requests
        subscribe<DocumentPtr>("document.process", [this](DocumentPtr doc) {
            processDocument(doc);
        });
    }
References processDocument(), and doc_system::Microservice::subscribe().
processDocument()
void doc_system::DocumentProcessingService::processDocument (DocumentPtr document) inline private
Definition at line 279 of file message_queue.h.
{
        if (!document) {
            return;
        }
        std::cout << "Processing document: " << document->getFilename() << std::endl;
        // Apply some processing to the document
        document->applyFormatting("corporate");
        // Notify that processing is complete
        publish("document.processed", document);
    }
References doc_system::Microservice::publish().
Referenced by initialize().
run()
void doc_system::DocumentProcessingService::run () inline override protected virtual
Implements doc_system::Microservice.
Definition at line 271 of file message_queue.h.
{
        while (running_) {
            // Service heartbeat or other periodic tasks
            std::this_thread::sleep_for(std::chrono::seconds(1));
        }
    }
References doc_system::Microservice::running_.
The documentation for this class was generated from the following file:
headers/message_queue.h