Document Processing System: doc_system::BaseDocument Class Reference
doc_system::BaseDocument Class Reference
#include <document_observer.h>
Public Member Functions
BaseDocument (const std::string &filename)
void attachObserver (ObserverPtr observer) override
void detachObserver (ObserverPtr observer) override
void notifyObservers (const std::string &eventType) override
std::string getFilename () const override
void updateContent (const std::string &newContent) override
void setHeader (const std::string &header) override
void setContent (const std::string &content) override
void setFooter (const std::string &footer) override
void setMetadata (const MetadataMap &metadata) override
Public Member Functions inherited from doc_system::Document
virtual ~Document ()=default
virtual DocumentType getType () const =0
virtual void save ()=0
virtual void load ()=0
virtual void applyFormatting (const std::string &strategyName)=0
virtual void applyRendering (const std::string &strategyName)=0
virtual void applyLayout (const std::string &strategyName)=0
Protected Attributes
std::string filename_
std::string header_
std::string content_
std::string footer_
MetadataMap metadata_
std::vector< ObserverPtr > observers_
Detailed Description
Definition at line 27 of file document_observer.h.
Constructor & Destructor Documentation
BaseDocument()
doc_system::BaseDocument::BaseDocument (const std::string & filename) inline explicit
Definition at line 29 of file document_observer.h.
: filename_(filename) {}
References filename_.
Referenced by doc_system::PdfDocument::PdfDocument(), doc_system::TextDocument::TextDocument(), and doc_system::WordDocument::WordDocument().
Member Function Documentation
attachObserver()
void doc_system::BaseDocument::attachObserver (ObserverPtr observer) inline override virtual
Implements doc_system::Document.
Definition at line 32 of file document_observer.h.
{
        if (observer) {
            auto it = std::find(observers_.begin(), observers_.end(), observer);
            if (it == observers_.end()) {
                observers_.push_back(observer);
            }
        }
    }
References observers_.
detachObserver()
void doc_system::BaseDocument::detachObserver (ObserverPtr observer) inline override virtual
Implements doc_system::Document.
Definition at line 41 of file document_observer.h.
{
        observers_.erase(
            std::remove(observers_.begin(), observers_.end(), observer),
            observers_.end()
        );
    }
References observers_.
getFilename()
std::string doc_system::BaseDocument::getFilename () const inline override virtual
Implements doc_system::Document.
Definition at line 55 of file document_observer.h.
{
        return filename_;
    }
References filename_.
notifyObservers()
void doc_system::BaseDocument::notifyObservers (const std::string & eventType) inline override virtual
Implements doc_system::Document.
Definition at line 48 of file document_observer.h.
{
        for (const auto& observer : observers_) {
            observer->onNotify(*this, eventType);
        }
    }
References observers_.
Referenced by doc_system::PdfDocument::load(), doc_system::TextDocument::load(), doc_system::WordDocument::load(), doc_system::PdfDocument::save(), doc_system::TextDocument::save(), doc_system::WordDocument::save(), and updateContent().
setContent()
void doc_system::BaseDocument::setContent (const std::string & content) inline override virtual
Implements doc_system::Document.
Definition at line 68 of file document_observer.h.
{
        content_ = content;
    }
References content_.
setFooter()
void doc_system::BaseDocument::setFooter (const std::string & footer) inline override virtual
Implements doc_system::Document.
Definition at line 72 of file document_observer.h.
{
        footer_ = footer;
    }
References footer_.
setHeader()
void doc_system::BaseDocument::setHeader (const std::string & header) inline override virtual
Implements doc_system::Document.
Definition at line 64 of file document_observer.h.
{
        header_ = header;
    }
References header_.
setMetadata()
void doc_system::BaseDocument::setMetadata (const MetadataMap & metadata) inline override virtual
Implements doc_system::Document.
Definition at line 76 of file document_observer.h.
{
        metadata_ = metadata;
    }
References metadata_.
updateContent()
void doc_system::BaseDocument::updateContent (const std::string & newContent) inline override virtual
Implements doc_system::Document.
Definition at line 59 of file document_observer.h.
{
        content_ = newContent;
        notifyObservers(events::DocumentChanged);
    }
References content_, doc_system::events::DocumentChanged, and notifyObservers().
Member Data Documentation
content_
std::string doc_system::BaseDocument::content_ protected
Definition at line 83 of file document_observer.h.
Referenced by setContent(), and updateContent().
filename_
std::string doc_system::BaseDocument::filename_ protected
Definition at line 81 of file document_observer.h.
Referenced by BaseDocument(), getFilename(), doc_system::PdfDocument::load(), doc_system::TextDocument::load(), doc_system::WordDocument::load(), doc_system::PdfDocument::save(), doc_system::TextDocument::save(), and doc_system::WordDocument::save().
footer_
std::string doc_system::BaseDocument::footer_ protected
Definition at line 84 of file document_observer.h.
Referenced by setFooter().
header_
std::string doc_system::BaseDocument::header_ protected
Definition at line 82 of file document_observer.h.
Referenced by setHeader().
metadata_
MetadataMap doc_system::BaseDocument::metadata_ protected
Definition at line 85 of file document_observer.h.
Referenced by setMetadata().
observers_
std::vector<ObserverPtr> doc_system::BaseDocument::observers_ protected
Definition at line 86 of file document_observer.h.
Referenced by attachObserver(), detachObserver(), and notifyObservers().
The documentation for this class was generated from the following file:
headers/document_observer.h