Document Processing System: doc_system::Document Class Reference
doc_system::Document Class Reference abstract
#include <document_types.h>
Public Member Functions
virtual ~Document ()=default
virtual DocumentType getType () const =0
virtual std::string getFilename () const =0
virtual void save ()=0
virtual void load ()=0
virtual void setHeader (const std::string &header)=0
virtual void setContent (const std::string &content)=0
virtual void setFooter (const std::string &footer)=0
virtual void setMetadata (const MetadataMap &metadata)=0
virtual void updateContent (const std::string &newContent)=0
virtual void attachObserver (ObserverPtr observer)=0
virtual void detachObserver (ObserverPtr observer)=0
virtual void notifyObservers (const std::string &eventType)=0
virtual void applyFormatting (const std::string &strategyName)=0
virtual void applyRendering (const std::string &strategyName)=0
virtual void applyLayout (const std::string &strategyName)=0
Detailed Description
Definition at line 44 of file document_types.h.
Constructor & Destructor Documentation
~Document()
virtual doc_system::Document::~Document () virtual default
Member Function Documentation
applyFormatting()
virtual void doc_system::Document::applyFormatting (const std::string & strategyName) pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
applyLayout()
virtual void doc_system::Document::applyLayout (const std::string & strategyName) pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
applyRendering()
virtual void doc_system::Document::applyRendering (const std::string & strategyName) pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
attachObserver()
virtual void doc_system::Document::attachObserver (ObserverPtr observer) pure virtual
Implemented in doc_system::BaseDocument.
detachObserver()
virtual void doc_system::Document::detachObserver (ObserverPtr observer) pure virtual
Implemented in doc_system::BaseDocument.
getFilename()
virtual std::string doc_system::Document::getFilename () const pure virtual
Implemented in doc_system::BaseDocument.
Referenced by doc_system::AcademicFormattingStrategy::format(), doc_system::CorporateFormattingStrategy::format(), doc_system::CompactLayoutStrategy::layout(), doc_system::GridLayoutStrategy::layout(), doc_system::AutoSaveObserver::onNotify(), doc_system::LoggingObserver::onNotify(), doc_system::ValidationObserver::onNotify(), TestObserver::onNotify(), doc_system::FastRenderingStrategy::render(), doc_system::HighQualityRenderingStrategy::render(), and TEST_F().
getType()
virtual DocumentType doc_system::Document::getType () const pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
load()
virtual void doc_system::Document::load () pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
notifyObservers()
virtual void doc_system::Document::notifyObservers (const std::string & eventType) pure virtual
Implemented in doc_system::BaseDocument.
save()
virtual void doc_system::Document::save () pure virtual
Implemented in doc_system::PdfDocument, doc_system::TextDocument, and doc_system::WordDocument.
setContent()
virtual void doc_system::Document::setContent (const std::string & content) pure virtual
Implemented in doc_system::BaseDocument.
setFooter()
virtual void doc_system::Document::setFooter (const std::string & footer) pure virtual
Implemented in doc_system::BaseDocument.
setHeader()
virtual void doc_system::Document::setHeader (const std::string & header) pure virtual
Implemented in doc_system::BaseDocument.
setMetadata()
virtual void doc_system::Document::setMetadata (const MetadataMap & metadata) pure virtual
Implemented in doc_system::BaseDocument.
updateContent()
virtual void doc_system::Document::updateContent (const std::string & newContent) pure virtual
Implemented in doc_system::BaseDocument.
The documentation for this class was generated from the following file:
headers/document_types.h