Document Processing System: doc_system::MessageQueue Class Reference
doc_system::MessageQueue Class Reference
#include <message_queue.h>
Public Member Functions
MessageQueue (const MessageQueue &)=delete
MessageQueue & operator= (const MessageQueue &)=delete
MessageQueue (MessageQueue &&)=delete
MessageQueue & operator= (MessageQueue &&)=delete
template<typename T>
void publish (const std::string &topic, T &&payload)
template<typename T>
void subscribe (const std::string &topic, std::function< void(T)> callback)
void startProcessing ()
void stopProcessing ()
void waitUntilEmpty ()
size_t getQueueSize () const
~MessageQueue ()
Static Public Member Functions
static MessageQueue & getInstance ()
Private Member Functions
MessageQueue ()
void processMessages ()
Message waitForMessage ()
void dispatchMessage (const Message &message)
Private Attributes
std::mutex queueMutex_
std::mutex subscriptionMutex_
std::condition_variable queueCondition_
std::condition_variable emptyCondition_
std::queue< Message > messageQueue_
std::unordered_map< std::string, std::vector< std::function< void(const Message &)> > > subscriptions_
std::thread processingThread_
std::atomic< bool > running_
Detailed Description
Definition at line 44 of file message_queue.h.
Constructor & Destructor Documentation
MessageQueue() [1/3]
doc_system::MessageQueue::MessageQueue (const MessageQueue &) delete
References MessageQueue().
Referenced by getInstance(), MessageQueue(), MessageQueue(), operator=(), and operator=().
MessageQueue() [2/3]
doc_system::MessageQueue::MessageQueue (MessageQueue &&) delete
References MessageQueue().
~MessageQueue()
doc_system::MessageQueue::~MessageQueue () inline
Definition at line 119 of file message_queue.h.
                    {
        stopProcessing();
    }
References stopProcessing().
MessageQueue() [3/3]
doc_system::MessageQueue::MessageQueue () inline private
Definition at line 124 of file message_queue.h.
: running_(false) {}
References running_.
Member Function Documentation
dispatchMessage()
void doc_system::MessageQueue::dispatchMessage (const Message & message) inline private
Definition at line 165 of file message_queue.h.
{
        std::vector<std::function<void(const Message&)>> callbacks;
        {
            std::lock_guard<std::mutex> lock(subscriptionMutex_);
            auto it = subscriptions_.find(message.topic);
            if (it != subscriptions_.end()) {
                callbacks = it->second;
            }
        }
        for (const auto& callback : callbacks) {
            callback(message);
        }
    }
References subscriptionMutex_, subscriptions_, and doc_system::Message::topic.
Referenced by processMessages().
getInstance()
static MessageQueue & doc_system::MessageQueue::getInstance () inline static
Definition at line 47 of file message_queue.h.
{
        static MessageQueue instance;
        return instance;
    }
References MessageQueue().
Referenced by main(), doc_system::Microservice::publish(), doc_system::Microservice::start(), and doc_system::Microservice::subscribe().
getQueueSize()
size_t doc_system::MessageQueue::getQueueSize () const inline
Definition at line 114 of file message_queue.h.
{
        std::lock_guard<std::mutex> lock(queueMutex_);
        return messageQueue_.size();
    }
References messageQueue_, and queueMutex_.
operator=() [1/2]
MessageQueue & doc_system::MessageQueue::operator= (const MessageQueue &) delete
References MessageQueue().
operator=() [2/2]
MessageQueue & doc_system::MessageQueue::operator= (MessageQueue &&) delete
References MessageQueue().
processMessages()
void doc_system::MessageQueue::processMessages () inline private
Definition at line 127 of file message_queue.h.
{
        while (running_) {
            Message currentMessage = waitForMessage();
            if (!running_) {
                break;
            }
            dispatchMessage(currentMessage);
            // Notify if the queue is empty
            {
                std::lock_guard<std::mutex> lock(queueMutex_);
                if (messageQueue_.empty()) {
                    emptyCondition_.notify_all();
                }
            }
        }
    }
References dispatchMessage(), emptyCondition_, messageQueue_, queueMutex_, running_, and waitForMessage().
Referenced by startProcessing().
publish()
template<typename T> void doc_system::MessageQueue::publish (const std::string & topic, T && payload) inline
Definition at line 60 of file message_queue.h.
{
        {
            std::lock_guard<std::mutex> lock(queueMutex_);
            messageQueue_.push(Message(topic, std::forward<T>(payload)));
        }
        queueCondition_.notify_one();
    }
References messageQueue_, queueCondition_, and queueMutex_.
Referenced by doc_system::Microservice::publish().
startProcessing()
void doc_system::MessageQueue::startProcessing () inline
Definition at line 84 of file message_queue.h.
{
        if (processingThread_.joinable()) {
            return; // Already running
        }
        running_ = true;
        processingThread_ = std::thread([this]() {
            this->processMessages();
        });
    }
References processingThread_, processMessages(), and running_.
Referenced by doc_system::Microservice::start().
stopProcessing()
void doc_system::MessageQueue::stopProcessing () inline
Definition at line 96 of file message_queue.h.
{
        running_ = false;
        queueCondition_.notify_all();
        if (processingThread_.joinable()) {
            processingThread_.join();
        }
    }
References processingThread_, queueCondition_, and running_.
Referenced by ~MessageQueue().
subscribe()
template<typename T> void doc_system::MessageQueue::subscribe (const std::string & topic, std::function< void(T)> callback) inline
Definition at line 71 of file message_queue.h.
{
        std::lock_guard<std::mutex> lock(subscriptionMutex_);
        auto wrappedCallback = [callback](const Message& msg) {
            if (msg.payloadType == typeid(T)) {
                callback(msg.getPayload<T>());
            }
        };
        subscriptions_[topic].push_back(wrappedCallback);
    }
References subscriptionMutex_, and subscriptions_.
Referenced by doc_system::Microservice::subscribe().
waitForMessage()
Message doc_system::MessageQueue::waitForMessage () inline private
Definition at line 148 of file message_queue.h.
{
        std::unique_lock<std::mutex> lock(queueMutex_);
        queueCondition_.wait(lock, [this]() {
            return !messageQueue_.empty() || !running_;
        });
        if (!running_) {
            return Message("", 0); // Dummy message
        }
        Message message = messageQueue_.front();
        messageQueue_.pop();
        return message;
    }
References messageQueue_, queueCondition_, queueMutex_, and running_.
Referenced by processMessages().
waitUntilEmpty()
void doc_system::MessageQueue::waitUntilEmpty () inline
Definition at line 106 of file message_queue.h.
{
        std::unique_lock<std::mutex> lock(queueMutex_);
        emptyCondition_.wait(lock, [this]() {
            return messageQueue_.empty();
        });
    }
References emptyCondition_, messageQueue_, and queueMutex_.
Member Data Documentation
emptyCondition_
std::condition_variable doc_system::MessageQueue::emptyCondition_ private
Definition at line 184 of file message_queue.h.
Referenced by processMessages(), and waitUntilEmpty().
messageQueue_
std::queue<Message> doc_system::MessageQueue::messageQueue_ private
Definition at line 185 of file message_queue.h.
Referenced by getQueueSize(), processMessages(), publish(), waitForMessage(), and waitUntilEmpty().
processingThread_
std::thread doc_system::MessageQueue::processingThread_ private
Definition at line 187 of file message_queue.h.
Referenced by startProcessing(), and stopProcessing().
queueCondition_
std::condition_variable doc_system::MessageQueue::queueCondition_ private
Definition at line 183 of file message_queue.h.
Referenced by publish(), stopProcessing(), and waitForMessage().
queueMutex_
std::mutex doc_system::MessageQueue::queueMutex_ mutable private
Definition at line 181 of file message_queue.h.
Referenced by getQueueSize(), processMessages(), publish(), waitForMessage(), and waitUntilEmpty().
running_
std::atomic<bool> doc_system::MessageQueue::running_ private
Definition at line 188 of file message_queue.h.
Referenced by MessageQueue(), processMessages(), startProcessing(), stopProcessing(), and waitForMessage().
subscriptionMutex_
std::mutex doc_system::MessageQueue::subscriptionMutex_ mutable private
Definition at line 182 of file message_queue.h.
Referenced by dispatchMessage(), and subscribe().
subscriptions_
std::unordered_map<std::string, std::vector<std::function<void(const Message&)> > > doc_system::MessageQueue::subscriptions_ private
Definition at line 186 of file message_queue.h.
Referenced by dispatchMessage(), and subscribe().
The documentation for this class was generated from the following file:
headers/message_queue.h