Document Processing System: doc_system::ImageRenderingStrategy Class Reference
doc_system::ImageRenderingStrategy Class Reference abstract
#include <document_strategy.h>
Public Member Functions
virtual ~ImageRenderingStrategy ()=default
virtual void render (Document &document)=0
Static Public Member Functions
static std::unique_ptr< ImageRenderingStrategy > create (const std::string &strategyType)
Detailed Description
Definition at line 27 of file document_strategy.h.
Constructor & Destructor Documentation
~ImageRenderingStrategy()
virtual doc_system::ImageRenderingStrategy::~ImageRenderingStrategy () virtual default
Member Function Documentation
create()
std::unique_ptr< ImageRenderingStrategy > doc_system::ImageRenderingStrategy::create (const std::string & strategyType) inline static
Definition at line 186 of file document_strategy.h.
{
    return StrategyRegistry::getInstance().createRenderingStrategy(strategyType);
}
References doc_system::StrategyRegistry::createRenderingStrategy(), and doc_system::StrategyRegistry::getInstance().
Referenced by doc_system::PdfDocument::applyRendering(), doc_system::TextDocument::applyRendering(), doc_system::WordDocument::applyRendering(), TEST_F(), and TEST_F().
render()
virtual void doc_system::ImageRenderingStrategy::render (Document & document) pure virtual
Implemented in doc_system::FastRenderingStrategy, and doc_system::HighQualityRenderingStrategy.
The documentation for this class was generated from the following file:
headers/document_strategy.h