Document Processing System: src/test_builder.cpp File Reference
test_builder.cpp File Reference
#include <gtest/gtest.h>
#include "document_builder.h"
#include "document_factory.h"
#include "concrete_documents.h"
#include "concrete_tools.h"
#include <vector>
#include <string>
Classes
class BuilderTest
Functions
TEST_F (BuilderTest, BuildsComponentsIndividually)
TEST_F (BuilderTest, SupportsMethodChaining)
TEST_F (BuilderTest, DirectorBuildsStandardDocument)
TEST_F (BuilderTest, DirectorBuildsMinimalDocument)
TEST_F (BuilderTest, DirectorBuildsBusinessDocument)
TEST_F (BuilderTest, GetDocumentReturnsBuiltDocument)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 127 of file test_builder.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/6]
TEST_F (BuilderTest , BuildsComponentsIndividually)
Definition at line 27 of file test_builder.cpp.
{
    // Build each component and check the build steps
    builder.buildHeader("Test Header");
    EXPECT_EQ(builder.getBuildSteps(), std::vector<std::string>{"Header"});
    builder.buildContent("Test Content");
    EXPECT_EQ(builder.getBuildSteps(), std::vector<std::string>({"Header", "Content"}));
    builder.buildFooter("Test Footer");
    EXPECT_EQ(builder.getBuildSteps(), std::vector<std::string>({"Header", "Content", "Footer"}));
    MetadataMap metadata = {{"author", "Test Author"}, {"date", "2025-03-05"}};
    builder.buildMetadata(metadata);
    EXPECT_EQ(builder.getBuildSteps(), std::vector<std::string>({"Header", "Content", "Footer", "Metadata"}));
}
TEST_F() [2/6]
TEST_F (BuilderTest , DirectorBuildsBusinessDocument)
Definition at line 98 of file test_builder.cpp.
{
    // Create a new builder
    DocumentBuilder businessBuilder;
    businessBuilder.reset(testDocument);
    // Build a business document using the director
    DocumentDirector::buildBusinessDocument(
        businessBuilder,
        "Business Header",
        "Business Content",
        {{"author", "Business User"}, {"department", "Finance"}}
    );
    // Verify business document has metadata first, then header, then content
    EXPECT_EQ(businessBuilder.getBuildSteps(),
              std::vector<std::string>({"Metadata", "Header", "Content"}));
}
References doc_system::DocumentDirector::buildBusinessDocument(), doc_system::DocumentBuilder::getBuildSteps(), and doc_system::DocumentBuilder::reset().
TEST_F() [3/6]
TEST_F (BuilderTest , DirectorBuildsMinimalDocument)
Definition at line 82 of file test_builder.cpp.
{
    // Create a new builder
    DocumentBuilder minimalBuilder;
    minimalBuilder.reset(testDocument);
    // Build a minimal document using the director
    DocumentDirector::buildMinimalDocument(
        minimalBuilder,
        "Minimal Content Only"
    );
    // Verify build order contains only content
    EXPECT_EQ(minimalBuilder.getBuildSteps(), std::vector<std::string>({"Content"}));
}
References doc_system::DocumentDirector::buildMinimalDocument(), doc_system::DocumentBuilder::getBuildSteps(), and doc_system::DocumentBuilder::reset().
TEST_F() [4/6]
TEST_F (BuilderTest , DirectorBuildsStandardDocument)
Definition at line 62 of file test_builder.cpp.
{
    // Create a new builder
    DocumentBuilder standardBuilder;
    standardBuilder.reset(testDocument);
    // Build a standard document using the director
    DocumentDirector::buildStandardDocument(
        standardBuilder,
        "Standard Header",
        "Standard Content",
        "Standard Footer",
        {{"key1", "value1"}, {"key2", "value2"}}
    );
    // Verify build order matches expected standard document flow
    EXPECT_EQ(standardBuilder.getBuildSteps(),
              std::vector<std::string>({"Header", "Content", "Footer", "Metadata"}));
}
References doc_system::DocumentDirector::buildStandardDocument(), doc_system::DocumentBuilder::getBuildSteps(), and doc_system::DocumentBuilder::reset().
TEST_F() [5/6]
TEST_F (BuilderTest , GetDocumentReturnsBuiltDocument)
Definition at line 117 of file test_builder.cpp.
{
    builder.buildHeader("Test Header")
           .buildContent("Test Content");
    auto result = builder.getDocument();
    // Check that we get back the original document
    EXPECT_EQ(result, testDocument);
}
TEST_F() [6/6]
TEST_F (BuilderTest , SupportsMethodChaining)
Definition at line 44 of file test_builder.cpp.
{
    // Create a new builder instance for this test
    DocumentBuilder chainBuilder;
    chainBuilder.reset(testDocument);
    // Method chaining call
    DocumentBuilder& result = chainBuilder.buildHeader("Test Header")
                                        .buildContent("Test Content")
                                        .buildFooter("Test Footer");
    // Check that method chaining returns the builder itself
    EXPECT_EQ(&result, &chainBuilder);
    // Check that the build steps are recorded in the correct order
    EXPECT_EQ(chainBuilder.getBuildSteps(), std::vector<std::string>({"Header", "Content", "Footer"}));
}
References doc_system::DocumentBuilder::buildContent(), doc_system::DocumentBuilder::buildFooter(), doc_system::DocumentBuilder::buildHeader(), doc_system::DocumentBuilder::getBuildSteps(), and doc_system::DocumentBuilder::reset().