Document Processing System: src/test_abstract_factory.cpp File Reference
test_abstract_factory.cpp File Reference
#include <gtest/gtest.h>
#include "abstract_factory.h"
#include "concrete_tools.h"
#include "document_factory.h"
#include <memory>
#include <tuple>
Classes
class AbstractFactoryTest
Functions
TEST_F (AbstractFactoryTest, CreatesCorrectFactory)
TEST_F (AbstractFactoryTest, CreatesCorrectToolTypes)
TEST_F (AbstractFactoryTest, CreatesCompatibleTools)
TEST_F (AbstractFactoryTest, ToolFactoryCreatesCompleteSets)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 121 of file test_abstract_factory.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/4]
TEST_F (AbstractFactoryTest , CreatesCompatibleTools)
Definition at line 76 of file test_abstract_factory.cpp.
{
    // PDF Tools
    auto pdfFactory = DocumentToolFactory::createFactory(DocumentType::PDF);
    auto pdfViewer = pdfFactory->createViewer();
    auto pdfEditor = pdfFactory->createEditor();
    // They should both support the same document type
    EXPECT_EQ(pdfViewer->getSupportedType(), pdfEditor->getSupportedType());
    // Test that tools work with the correct document type
    EXPECT_NO_THROW(pdfViewer->view(pdfDocument));
    EXPECT_NO_THROW(pdfEditor->edit(pdfDocument));
    // Test that tools throw for incompatible document types
    EXPECT_THROW(pdfViewer->view(wordDocument), std::invalid_argument);
    EXPECT_THROW(pdfEditor->edit(textDocument), std::invalid_argument);
}
References doc_system::DocumentToolFactory::createFactory(), and doc_system::PDF.
TEST_F() [2/4]
TEST_F (AbstractFactoryTest , CreatesCorrectFactory)
Definition at line 28 of file test_abstract_factory.cpp.
{
    auto pdfFactory = DocumentToolFactory::createFactory(DocumentType::PDF);
    auto wordFactory = DocumentToolFactory::createFactory(DocumentType::Word);
    auto textFactory = DocumentToolFactory::createFactory(DocumentType::Text);
    // Verify factory types using dynamic_cast
    EXPECT_NE(dynamic_cast<PdfToolFactory*>(pdfFactory.get()), nullptr);
    EXPECT_NE(dynamic_cast<WordToolFactory*>(wordFactory.get()), nullptr);
    EXPECT_NE(dynamic_cast<TextToolFactory*>(textFactory.get()), nullptr);
    // Verify factory throws for unknown types
    EXPECT_THROW(DocumentToolFactory::createFactory(DocumentType::Unknown), std::invalid_argument);
}
References doc_system::DocumentToolFactory::createFactory(), doc_system::PDF, doc_system::Text, doc_system::Unknown, and doc_system::Word.
TEST_F() [3/4]
TEST_F (AbstractFactoryTest , CreatesCorrectToolTypes)
Definition at line 43 of file test_abstract_factory.cpp.
{
    // PDF Tools
    auto pdfFactory = DocumentToolFactory::createFactory(DocumentType::PDF);
    auto pdfViewer = pdfFactory->createViewer();
    auto pdfEditor = pdfFactory->createEditor();
    auto pdfConverter = pdfFactory->createConverter();
    EXPECT_EQ(pdfViewer->getSupportedType(), DocumentType::PDF);
    EXPECT_EQ(pdfEditor->getSupportedType(), DocumentType::PDF);
    EXPECT_EQ(pdfConverter->getSourceType(), DocumentType::PDF);
    // Word Tools
    auto wordFactory = DocumentToolFactory::createFactory(DocumentType::Word);
    auto wordViewer = wordFactory->createViewer();
    auto wordEditor = wordFactory->createEditor();
    auto wordConverter = wordFactory->createConverter();
    EXPECT_EQ(wordViewer->getSupportedType(), DocumentType::Word);
    EXPECT_EQ(wordEditor->getSupportedType(), DocumentType::Word);
    EXPECT_EQ(wordConverter->getSourceType(), DocumentType::Word);
    // Text Tools
    auto textFactory = DocumentToolFactory::createFactory(DocumentType::Text);
    auto textViewer = textFactory->createViewer();
    auto textEditor = textFactory->createEditor();
    auto textConverter = textFactory->createConverter();
    EXPECT_EQ(textViewer->getSupportedType(), DocumentType::Text);
    EXPECT_EQ(textEditor->getSupportedType(), DocumentType::Text);
    EXPECT_EQ(textConverter->getSourceType(), DocumentType::Text);
}
References doc_system::DocumentToolFactory::createFactory(), doc_system::PDF, doc_system::Text, and doc_system::Word.
TEST_F() [4/4]
TEST_F (AbstractFactoryTest , ToolFactoryCreatesCompleteSets)
Definition at line 95 of file test_abstract_factory.cpp.
{
    // Create tools for PDF document
    auto [pdfViewer, pdfEditor, pdfConverter] = ToolFactory::createToolsFor(DocumentType::PDF);
    // Verify tool types
    EXPECT_EQ(pdfViewer->getSupportedType(), DocumentType::PDF);
    EXPECT_EQ(pdfEditor->getSupportedType(), DocumentType::PDF);
    EXPECT_EQ(pdfConverter->getSourceType(), DocumentType::PDF);
    // Create tools for Word document
    auto [wordViewer, wordEditor, wordConverter] = ToolFactory::createToolsFor(DocumentType::Word);
    // Verify tool types
    EXPECT_EQ(wordViewer->getSupportedType(), DocumentType::Word);
    EXPECT_EQ(wordEditor->getSupportedType(), DocumentType::Word);
    EXPECT_EQ(wordConverter->getSourceType(), DocumentType::Word);
    // Create tools for Text document
    auto [textViewer, textEditor, textConverter] = ToolFactory::createToolsFor(DocumentType::Text);
    // Verify tool types
    EXPECT_EQ(textViewer->getSupportedType(), DocumentType::Text);
    EXPECT_EQ(textEditor->getSupportedType(), DocumentType::Text);
    EXPECT_EQ(textConverter->getSourceType(), DocumentType::Text);
}
References doc_system::ToolFactory::createToolsFor(), doc_system::PDF, doc_system::Text, and doc_system::Word.