Document Processing System: src/test_factory.cpp File Reference
test_factory.cpp File Reference
#include <gtest/gtest.h>
#include "document_factory.h"
#include "concrete_documents.h"
Classes
class FactoryMethodTest
Functions
TEST_F (FactoryMethodTest, CreatesPdfDocumentForPdfExtension)
TEST_F (FactoryMethodTest, CreatesWordDocumentForWordExtensions)
TEST_F (FactoryMethodTest, CreatesTextDocumentForTxtExtension)
TEST_F (FactoryMethodTest, ThrowsForUnsupportedExtension)
TEST_F (FactoryMethodTest, HandlesComplexFilenames)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 80 of file test_factory.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/5]
TEST_F (FactoryMethodTest , CreatesPdfDocumentForPdfExtension)
Definition at line 23 of file test_factory.cpp.
{
    // Test with uppercase extension
    auto doc1 = DocumentFactory::createDocument("test.PDF");
    EXPECT_EQ(doc1->getType(), DocumentType::PDF);
    EXPECT_EQ(doc1->getFilename(), "test.PDF");
    // Test with lowercase extension
    auto doc2 = DocumentFactory::createDocument("report.pdf");
    EXPECT_EQ(doc2->getType(), DocumentType::PDF);
    EXPECT_EQ(doc2->getFilename(), "report.pdf");
}
References doc_system::DocumentFactory::createDocument(), and doc_system::PDF.
TEST_F() [2/5]
TEST_F (FactoryMethodTest , CreatesTextDocumentForTxtExtension)
Definition at line 49 of file test_factory.cpp.
{
    auto doc = DocumentFactory::createDocument("notes.txt");
    EXPECT_EQ(doc->getType(), DocumentType::Text);
    EXPECT_EQ(doc->getFilename(), "notes.txt");
}
References doc_system::DocumentFactory::createDocument(), and doc_system::Text.
TEST_F() [3/5]
TEST_F (FactoryMethodTest , CreatesWordDocumentForWordExtensions)
Definition at line 36 of file test_factory.cpp.
{
    // Test .docx extension
    auto doc1 = DocumentFactory::createDocument("test.docx");
    EXPECT_EQ(doc1->getType(), DocumentType::Word);
    EXPECT_EQ(doc1->getFilename(), "test.docx");
    // Test .doc extension
    auto doc2 = DocumentFactory::createDocument("old_report.doc");
    EXPECT_EQ(doc2->getType(), DocumentType::Word);
    EXPECT_EQ(doc2->getFilename(), "old_report.doc");
}
References doc_system::DocumentFactory::createDocument(), and doc_system::Word.
TEST_F() [4/5]
TEST_F (FactoryMethodTest , HandlesComplexFilenames)
Definition at line 63 of file test_factory.cpp.
{
    // Test filename with path
    auto doc1 = DocumentFactory::createDocument("/path/to/document.pdf");
    EXPECT_EQ(doc1->getType(), DocumentType::PDF);
    EXPECT_EQ(doc1->getFilename(), "/path/to/document.pdf");
    // Test filename with spaces
    auto doc2 = DocumentFactory::createDocument("My Document.docx");
    EXPECT_EQ(doc2->getType(), DocumentType::Word);
    EXPECT_EQ(doc2->getFilename(), "My Document.docx");
    // Test filename with multiple dots
    auto doc3 = DocumentFactory::createDocument("version.1.2.final.txt");
    EXPECT_EQ(doc3->getType(), DocumentType::Text);
    EXPECT_EQ(doc3->getFilename(), "version.1.2.final.txt");
}
References doc_system::DocumentFactory::createDocument(), doc_system::PDF, doc_system::Text, and doc_system::Word.
TEST_F() [5/5]
TEST_F (FactoryMethodTest , ThrowsForUnsupportedExtension)
Definition at line 56 of file test_factory.cpp.
{
    EXPECT_THROW(DocumentFactory::createDocument("image.jpg"), std::invalid_argument);
    EXPECT_THROW(DocumentFactory::createDocument("data.csv"), std::invalid_argument);
    EXPECT_THROW(DocumentFactory::createDocument("noextension"), std::invalid_argument);
}
References doc_system::DocumentFactory::createDocument().