Document Processing System: src/test_strategy.cpp File Reference
test_strategy.cpp File Reference
#include <gtest/gtest.h>
#include "document_strategy.h"
#include "document_factory.h"
#include "concrete_documents.h"
#include "concrete_tools.h"
Classes
class StrategyTest
Functions
TEST_F (StrategyTest, CreatesAndAppliesFormattingStrategies)
TEST_F (StrategyTest, CreatesAndAppliesRenderingStrategies)
TEST_F (StrategyTest, CreatesAndAppliesLayoutStrategies)
TEST_F (StrategyTest, ThrowsForUnknownStrategyNames)
TEST_F (StrategyTest, RegistersAndUsesCustomStrategies)
TEST_F (StrategyTest, AppliesStrategiesThroughDocumentInterface)
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
Definition at line 153 of file test_strategy.cpp.
{
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
TEST_F() [1/6]
TEST_F (StrategyTest , AppliesStrategiesThroughDocumentInterface)
Definition at line 127 of file test_strategy.cpp.
{
    // Apply formatting through document interface
    document->applyFormatting("corporate");
    std::string output = buffer.str();
    EXPECT_TRUE(output.find("Applying corporate formatting") != std::string::npos);
    // Clear buffer for next test
    clearBuffer();
    // Apply rendering through document interface
    document->applyRendering("high-quality");
    output = buffer.str();
    EXPECT_TRUE(output.find("Applying high-quality rendering") != std::string::npos);
    // Clear buffer for next test
    clearBuffer();
    // Apply layout through document interface
    document->applyLayout("grid");
    output = buffer.str();
    EXPECT_TRUE(output.find("Applying grid layout") != std::string::npos);
}
TEST_F() [2/6]
TEST_F (StrategyTest , CreatesAndAppliesFormattingStrategies)
Definition at line 39 of file test_strategy.cpp.
{
    // Create and apply corporate formatting strategy
    auto corporateStrategy = TextFormattingStrategy::create("corporate");
    corporateStrategy->format(*document);
    std::string output = buffer.str();
    EXPECT_TRUE(output.find("Applying corporate formatting") != std::string::npos);
    // Clear buffer for next test
    clearBuffer();
    // Create and apply academic formatting strategy
    auto academicStrategy = TextFormattingStrategy::create("academic");
    academicStrategy->format(*document);
    output = buffer.str();
    EXPECT_TRUE(output.find("Applying academic formatting") != std::string::npos);
}
References doc_system::TextFormattingStrategy::create().
TEST_F() [3/6]
TEST_F (StrategyTest , CreatesAndAppliesLayoutStrategies)
Definition at line 79 of file test_strategy.cpp.
{
    // Create and apply grid layout strategy
    auto gridStrategy = TableLayoutStrategy::create("grid");
    gridStrategy->layout(*document);
    std::string output = buffer.str();
    EXPECT_TRUE(output.find("Applying grid layout") != std::string::npos);
    // Clear buffer for next test
    clearBuffer();
    // Create and apply compact layout strategy
    auto compactStrategy = TableLayoutStrategy::create("compact");
    compactStrategy->layout(*document);
    output = buffer.str();
    EXPECT_TRUE(output.find("Applying compact layout") != std::string::npos);
}
References doc_system::TableLayoutStrategy::create().
TEST_F() [4/6]
TEST_F (StrategyTest , CreatesAndAppliesRenderingStrategies)
Definition at line 59 of file test_strategy.cpp.
{
    // Create and apply high-quality rendering strategy
    auto highQualityStrategy = ImageRenderingStrategy::create("high-quality");
    highQualityStrategy->render(*document);
    std::string output = buffer.str();
    EXPECT_TRUE(output.find("Applying high-quality rendering") != std::string::npos);
    // Clear buffer for next test
    clearBuffer();
    // Create and apply fast rendering strategy
    auto fastStrategy = ImageRenderingStrategy::create("fast");
    fastStrategy->render(*document);
    output = buffer.str();
    EXPECT_TRUE(output.find("Applying fast rendering") != std::string::npos);
}
References doc_system::ImageRenderingStrategy::create().
TEST_F() [5/6]
TEST_F (StrategyTest , RegistersAndUsesCustomStrategies)
Definition at line 106 of file test_strategy.cpp.
{
    // Create a custom formatting strategy
    class CustomFormattingStrategy : public TextFormattingStrategy {
    public:
        void format(Document& document) override {
            std::cout << "Applying custom formatting to " << document.getFilename() << std::endl;
        }
    };
    // Register the custom strategy
    StrategyRegistry::getInstance().registerFormattingStrategy<CustomFormattingStrategy>("custom");
    // Create and apply the custom strategy
    auto customStrategy = TextFormattingStrategy::create("custom");
    customStrategy->format(*document);
    std::string output = buffer.str();
    EXPECT_TRUE(output.find("Applying custom formatting") != std::string::npos);
}
References doc_system::TextFormattingStrategy::create(), doc_system::TextFormattingStrategy::format(), doc_system::Document::getFilename(), doc_system::StrategyRegistry::getInstance(), and doc_system::StrategyRegistry::registerFormattingStrategy().
TEST_F() [6/6]
TEST_F (StrategyTest , ThrowsForUnknownStrategyNames)
Definition at line 99 of file test_strategy.cpp.
{
    EXPECT_THROW(TextFormattingStrategy::create("unknown"), std::invalid_argument);
    EXPECT_THROW(ImageRenderingStrategy::create("unknown"), std::invalid_argument);
    EXPECT_THROW(TableLayoutStrategy::create("unknown"), std::invalid_argument);
}
References doc_system::ImageRenderingStrategy::create(), doc_system::TableLayoutStrategy::create(), and doc_system::TextFormattingStrategy::create().